# Generated by Django 6.0.1 on 2026-01-06 21:34

import datetime

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("itunes_genre_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("send_email_notifications", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rss",
                    models.URLField(
                        max_length=2083,
                        unique=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive podcasts will no longer be updated from their RSS feeds.",
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False, help_text="Only available to subscribers"
                    ),
                ),
                ("etag", models.TextField(blank=True)),
                ("title", models.TextField(blank=True)),
                ("pub_date", models.DateTimeField(blank=True, null=True)),
                ("num_episodes", models.PositiveIntegerField(default=0)),
                ("parsed", models.DateTimeField(blank=True, null=True)),
                (
                    "feed_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("not_modified", "Not Modified"),
                            ("database_error", "Database Error"),
                            ("discontinued", "Discontinued"),
                            ("duplicate", "Duplicate"),
                            ("invalid_rss", "Invalid RSS"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frequency", models.DurationField(default=datetime.timedelta(days=1))),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("exception", models.TextField(blank=True)),
                ("num_retries", models.PositiveIntegerField(default=0)),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "funding_url",
                    models.URLField(
                        blank=True,
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("funding_text", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        default="en",
                        max_length=2,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("keywords", models.TextField(blank=True)),
                ("extracted_text", models.TextField(blank=True)),
                ("owner", models.TextField(blank=True)),
                ("promoted", models.BooleanField(default=False)),
                (
                    "podcast_type",
                    models.CharField(
                        choices=[("episodic", "Episodic"), ("serial", "Serial")],
                        default="episodic",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "owner_search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "canonical",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="simplecasts.podcast",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="podcasts", to="simplecasts.category"
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommended_podcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "episode_type",
                    models.CharField(
                        choices=[
                            ("full", "Full episode"),
                            ("trailer", "Trailer"),
                            ("bonus", "Bonus"),
                        ],
                        default="full",
                        max_length=12,
                    ),
                ),
                ("episode", models.IntegerField(blank=True, null=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                (
                    "media_url",
                    models.URLField(
                        max_length=2083,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("media_type", models.CharField(max_length=60)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="File size in bytes"
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=30)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "search_document",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="simplecasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=100, null=True
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="simplecasts.podcast",
                    ),
                ),
                (
                    "recommended",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar",
                        to="simplecasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="simplecasts.podcast",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="simplecasts.episode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "episode"],
                        name="simplecasts_user_id_5840b2_idx",
                    ),
                    models.Index(
                        fields=["user", "created"],
                        include=("episode_id",),
                        name="simplecasts_bookmark_desc_idx",
                    ),
                    models.Index(
                        fields=["user", "-created"],
                        include=("episode_id",),
                        name="simplecasts_bookmark_asc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "episode"),
                        name="unique_simplecasts_bookmark_user_episode",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listened", models.DateTimeField()),
                ("current_time", models.PositiveIntegerField(default=0)),
                ("duration", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_logs",
                        to="simplecasts.episode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "episode"],
                        name="simplecasts_user_id_8cf983_idx",
                    ),
                    models.Index(
                        fields=["user", "listened"],
                        include=("episode_id",),
                        name="simplecasts_audiolog_desc_idx",
                    ),
                    models.Index(
                        fields=["user", "-listened"],
                        include=("episode_id",),
                        name="simplecasts_audiolog_asc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "episode"),
                        name="unique_simplecasts_audiolog_user_episode",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-pub_date"], name="simplecasts_pub_dat_74abec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-promoted", "language", "-pub_date"],
                name="simplecasts_promote_2ab115_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["active", "-promoted", "parsed", "updated"],
                name="simplecasts_active_89dae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                condition=models.Q(("private", False), ("pub_date__isnull", False)),
                fields=["-pub_date"],
                name="simplecasts_podcast_public_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="simplecasts_search__5a4124_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["owner_search_document"], name="simplecasts_owner_s_b40637_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "pub_date", "id"],
                name="simplecasts_podcast_1111db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "-pub_date", "-id"],
                name="simplecasts_podcast_0ff5cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "season", "-pub_date", "-id"],
                name="simplecasts_podcast_c440f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["pub_date", "id"], name="simplecasts_pub_dat_e63d62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["-pub_date", "-id"], name="simplecasts_pub_dat_9acc44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(fields=["guid"], name="simplecasts_guid_bbb042_idx"),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="simplecasts_search__8ab6de_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(
                fields=("podcast", "guid"),
                name="unique_simplecasts_episode_podcast_guid",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["-score"], name="simplecasts_score_866794_idx"),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("podcast", "recommended"),
                name="unique_simplecasts_recommendation",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["-created"], name="simplecasts_created_dffa8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "podcast"),
                name="unique_simplecasts_subscription_user_podcast",
            ),
        ),
    ]
