# Generated by Django 6.0.1 on 2026-01-06 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simplecasts", "0001_initial"),
    ]

    operations = [
        # Podcast: owner_search_document trigger on owner field
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER podcast_update_owner_search_trigger
            BEFORE INSERT OR UPDATE OF owner ON simplecasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
                owner_search_document, 'pg_catalog.simple', owner
            );
            """,
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_owner_search_trigger ON simplecasts_podcast;",
        ),
        # Podcast: search_document trigger on title, owner, keywords fields
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER podcast_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, owner, keywords ON simplecasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
                search_document, 'pg_catalog.simple', title, owner, keywords
            );
            """,
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON simplecasts_podcast;",
        ),
        # Episode: search_document trigger on title, keywords fields
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER episode_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, keywords ON simplecasts_episode
            FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
                search_document, 'pg_catalog.simple', title, keywords
            );
            """,
            reverse_sql="DROP TRIGGER IF EXISTS episode_update_search_trigger ON simplecasts_episode;",
        ),
    ]
