# Generated by Django 6.0 on 2026-01-06 12:44

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simplecasts", "0002_create_search_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
