# Generated by Django 6.0 on 2026-01-06 12:45

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simplecasts", "0003_alter_episode_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="owner_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
