# Generated by Django 6.0 on 2026-01-06 13:06

from django.db import migrations

"""
https://github.com/AquaChocomint/AppleStore-Genre-ID
"""


_CATEGORIES = (
    ("After Shows", 1562),
    ("Alternative Health", 1513),
    ("Animation & Manga", 1510),
    ("Arts", 1301),
    ("Astronomy", 1538),
    ("Automotive", 1503),
    ("Aviation", 1504),
    ("Baseball", 1549),
    ("Basketball", 1548),
    ("Books", 1482),
    ("Buddhism", 1438),
    ("Business", 1321),
    ("Business News", 1490),
    ("Careers", 1410),
    ("Chemistry", 1539),
    ("Christianity", 1439),
    ("Comedy", 1303),
    ("Comedy Fiction", 1486),
    ("Comedy Interviews", 1496),
    ("Courses", 1501),
    ("Crafts", 1506),
    ("Cricket", 1554),
    ("Daily News", 1526),
    ("Design", 1402),
    ("Documentary", 1543),
    ("Drama", 1484),
    ("Earth Sciences", 1540),
    ("Education", 1304),
    ("Education for Kids", 1519),
    ("Entertainment News", 1531),
    ("Entrepreneurship", 1493),
    ("Fantasy Sports", 1560),
    ("Fashion & Beauty", 1459),
    ("Fiction", 1483),
    ("Film History", 1564),
    ("Film Interviews", 1565),
    ("Film Reviews", 1563),
    ("Fitness", 1514),
    ("Food", 1306),
    ("Football", 1547),
    ("Games", 1507),
    ("Golf", 1553),
    ("Government", 1511),
    ("Health & Fitness", 1512),
    ("Hinduism", 1463),
    ("History", 1487),
    ("Hobbies", 1505),
    ("Hockey", 1550),
    ("Home & Garden", 1508),
    ("How-To", 1499),
    ("Improv", 1495),
    ("Investing", 1412),
    ("Islam", 1440),
    ("Judaism", 1441),
    ("Kids & Family", 1305),
    ("Language Learning", 1498),
    ("Leisure", 1502),
    ("Life Sciences", 1541),
    ("Management", 1491),
    ("Marketing", 1492),
    ("Mathematics", 1536),
    ("Medicine", 1518),
    ("Mental Health", 1517),
    ("Music", 1310),
    ("Music Commentary", 1523),
    ("Music History", 1524),
    ("Music Interviews", 1525),
    ("Natural Sciences", 1534),
    ("Nature", 1537),
    ("News", 1489),
    ("News Commentary", 1530),
    ("Non-Profit", 1494),
    ("Nutrition", 1515),
    ("Parenting", 1521),
    ("Performing Arts", 1405),
    ("Personal Journals", 1302),
    ("Pets & Animals", 1522),
    ("Philosophy", 1443),
    ("Physics", 1542),
    ("Places & Travel", 1320),
    ("Politics", 1527),
    ("Relationships", 1544),
    ("Religion", 1532),
    ("Religion & Spirituality", 1314),
    ("Rugby", 1552),
    ("Running", 1551),
    ("Science", 1533),
    ("Science Fiction", 1485),
    ("Self-Improvement", 1500),
    ("Sexuality", 1516),
    ("Soccer", 1546),
    ("Social Sciences", 1535),
    ("Society & Culture", 1324),
    ("Spirituality", 1444),
    ("Sports", 1545),
    ("Sports News", 1529),
    ("Stand-Up", 1497),
    ("Stories for Kids", 1520),
    ("Swimming", 1558),
    ("Tech News", 1528),
    ("Technology", 1318),
    ("Tennis", 1556),
    ("True Crime", 1488),
    ("TV & Film", 1309),
    ("TV Reviews", 1561),
    ("Video Games", 1509),
    ("Visual Arts", 1406),
    ("Volleyball", 1557),
    ("Wilderness", 1559),
    ("Wrestling", 1555),
)


def _add_categories(apps, schema_editor):
    Category = apps.get_model("simplecasts.Category")
    categories = [
        Category(name=name, itunes_genre_id=itunes_genre_id)
        for name, itunes_genre_id in _CATEGORIES
    ]
    Category.objects.bulk_create(categories, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("simplecasts", "0004_alter_podcast_owner_search_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(_add_categories, reverse_code=migrations.RunPython.noop),
    ]
