# Generated by Django 5.1.6 on 2025-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0008_alter_episode_file_size"),
        ("podcasts", "0013_podcast_podcast_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_pub_dat_9b17cd_idx",
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["episode", "pub_date"], name="episodes_ep_episode_c8cf94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["-episode", "-pub_date"], name="episodes_ep_episode_ddf08c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["season", "episode", "pub_date"],
                name="episodes_ep_season_ec7620_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["-season", "-episode", "-pub_date"],
                name="episodes_ep_season_2b409f_idx",
            ),
        ),
    ]
