# Generated by Django 5.1.6 on 2025-02-26 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0009_remove_episode_episodes_ep_pub_dat_9b17cd_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_episode_c8cf94_idx",
        ),
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_episode_ddf08c_idx",
        ),
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_season_ec7620_idx",
        ),
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_season_2b409f_idx",
        ),
    ]
