# Generated by Django 5.2.6 on 2025-09-26 10:18

from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations, models

timeout_statement = "SET statement_timeout = 0;"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("episodes", "0015_remove_episode_episodes_ep_pub_dat_60d1c1_idx_and_more"),
        ("podcasts", "0045_remove_podcast_podcasts_po_itunes__d69e24_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(timeout_statement, reverse_sql=timeout_statement),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_podcast_12cd3c_idx",
        ),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_podcast_c43bb8_idx",
        ),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["pub_date", "podcast", "id"],
                name="episodes_ep_pub_dat_34887e_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["-pub_date", "podcast", "-id"],
                name="episodes_ep_pub_dat_4abe4c_idx",
            ),
        ),
    ]
