cronjobs:
    - name: "clear-sessions"
      schedule: "{{ cron_schedules.clear_sessions }}"
      command: "{{ manage_cmd }} clearsessions"

    - name: "create-recommendations"
      schedule: "{{ cron_schedules.create_recommendations }}"
      command: "{{ manage_cmd }} create_recommendations"

    - name: "fetch-top-itunes"
      schedule: "{{ cron_schedules.fetch_top_itunes }}"
      command: "{{ manage_cmd }} fetch_top_itunes -p {{ itunes_chart_country }}"

    - name: "parse-feeds"
      schedule: "{{ cron_schedules.parse_feeds }}"
      command: "{{ manage_cmd }} parse_feeds"

    - name: "send-notifications"
      schedule: "{{ cron_schedules.send_notifications }}"
      command: "{{ manage_cmd }} send_notifications"

    - name: "send-recommendations"
      schedule: "{{ cron_schedules.send_recommendations }}"
      command: "{{ manage_cmd }} send_recommendations"

configmap:
   - name: "admins"
     value: "{{ admins }}"

   - name: "admin_site_header"
     value: "{{ admin_site_header }}"

   - name: "admin_url"
     value: "{{ admin_url }}"

   - name: "allowed_hosts"
     value: "{{ allowed_hosts }}"

   - name: "conn_pool_max_idle"
     value: "{{ conn_pool_max_idle }}"

   - name: "conn_pool_max_lifetime"
     value: "{{ conn_pool_max_lifetime }}"

   - name: "conn_pool_max_waiting"
     value: "{{ conn_pool_max_waiting }}"

   - name: "conn_pool_max_size"
     value: "{{ conn_pool_max_size }}"

   - name: "conn_pool_min_size"
     value: "{{ conn_pool_min_size }}"

   - name: "contact_email"
     value: "{{ contact_email }}"

   - name: "csp_script_whitelist"
     value: "{{ csp_script_whitelist }}"

   - name: "mailgun_api_url"
     value: "{{ mailgun_api_url }}"

   - name: "mailgun_sender_domain"
     value: "{{ mailgun_sender_domain }}"

   - name: "meta_author"
     value: "{{ meta_author }}"

   - name: "meta_copyright"
     value: "{{ meta_copyright }}"

   - name: "meta_description"
     value: "{{ meta_description }}"

   - name: "meta_keywords"
     value: "{{ meta_keywords }}"

   - name: "secure_ssl_redirect"
     value: "{{ secure_ssl_redirect }}"


secrets:
  - name: "database_url"
    value: "{{ database_url }}"

  - name: "mailgun_api_key"
    value: "{{ mailgun_api_key }}"

  - name: "postgres_password"
    value: "{{ postgres_password }}"

  - name: "pwa_sha256_fingerprints"
    value: "{{ pwa_sha256_fingerprints }}"

  - name: "redis_url"
    value: "{{ redis_url }}"

  - name: "secret_key"
    value: "{{ secret_key }}"

  - name: "secret_key_fallbacks"
    value: "{{ secret_key_fallbacks }}"

  - name: "sentry_url"
    value: "{{ sentry_url }}"
