# Generated by Django 5.0.6 on 2024-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0003_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
