# Generated by Django 5.1.5 on 2025-01-15 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0010_podcast_itunes_ranking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["itunes_ranking"], name="podcasts_po_itunes__8b4558_idx"
            ),
        ),
    ]
