# Generated by Django 5.2.2 on 2025-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0036_remove_recommendation_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="itunes_ranking",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
