# Generated by Django 5.2.8 on 2025-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0049_set_podcast_num_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="has_similar_podcasts",
            field=models.BooleanField(default=False),
        ),
    ]
