# Generated by Django 5.2.8 on 2025-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0053_remove_podcast_podcasts_po_score_aeb891_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="itunes_genre_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
