# Generated by Django 5.2.8 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0055_itunes_genre_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
