# Generated by Django 6.0 on 2025-12-09 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0071_podcast_queued"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_54fdb6_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_active_b74445_idx",
        ),
        migrations.AddField(
            model_name="podcast",
            name="promoted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["promoted_at", "language", "-pub_date"],
                name="podcasts_po_promote_a84cd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["active", "-promoted_at", "parsed", "updated"],
                name="podcasts_po_active_aed488_idx",
            ),
        ),
    ]
