# Generated by Django 6.0 on 2025-12-09 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0075_remove_podcast_podcasts_po_active_aed488_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
