# Generated by Django 6.0 on 2025-12-09 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0081_remove_category_podcasts_ca_name_604e91_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS category_update_search_trigger ON podcasts_category;",
            reverse_sql="""
CREATE TRIGGER category_update_search_trigger
BEFORE INSERT OR UPDATE OF name ON podcasts_category
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.simple', name
);
UPDATE podcasts_category SET name = name;""",
        )
    ]
