# Generated by Django 6.0 on 2025-12-20 14:14

from django.db import migrations


def update_feed_status(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(
        feed_status__in=(
            "transient_http_error",
            "permanent_http_error",
        )
    ).update(feed_status="network_error")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0095_alter_podcast_feed_status"),
    ]

    operations = [
        migrations.RunPython(
            update_feed_status,
            reverse_code=migrations.RunPython.noop,
        )
    ]
