# Generated by Django 6.0 on 2025-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0098_remove_podcast_feed_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="feed_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
