# Generated by Django 6.0 on 2025-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0102_remove_podcast_traceback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="exception",
            field=models.TextField(blank=True),
        ),
    ]
