# Generated by Django 6.0 on 2025-12-22 11:50

from django.db import migrations
from django.db.models import F


def update_feed_status(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")

    # If exception set to "error"
    Podcast.objects.exclude(exception="").update(feed_status="error")

    # If inactive + canonical_id not NULL, set to "duplicate"
    Podcast.objects.filter(active=False, canonical__isnull=False).update(
        feed_status="duplicate"
    )

    # If inactive + canonical_id is NULL, set to "discontinued"

    Podcast.objects.filter(active=False, canonical__isnull=True).update(
        feed_status="discontinued"
    )

    # Any with active=True and exception ="" and parsed == feed_last_updated, set to "success"
    Podcast.objects.filter(
        active=True,
        exception="",
        parsed=F("feed_last_updated"),
    ).update(feed_status="success")

    # Any with active=True and exception ="" and parsed != feed_last_updated, set to "not_modified"
    #
    Podcast.objects.filter(
        active=True,
        exception="",
    ).exclude(
        parsed=F("feed_last_updated"),
    ).update(feed_status="not_modified")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0104_podcast_feed_status"),
    ]

    operations = [
        migrations.RunPython(
            update_feed_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
