# Generated by Django 6.0 on 2025-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0105_update_feed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_retries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("not_modified", "Not Modified"),
                    ("discontinued", "Discontinued"),
                    ("duplicate", "Duplicate"),
                    ("invalid_rss", "Invalid RSS"),
                    ("unavailable", "Unavailable"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
