# Generated by Django 6.0 on 2025-12-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0108_update_feed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("not_modified", "Not Modified"),
                    ("database_error", "Database Error"),
                    ("discontinued", "Discontinued"),
                    ("duplicate", "Duplicate"),
                    ("invalid_rss", "Invalid RSS"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
