# Created with podman-4.6.2
# Intended for local development use
apiVersion: v1
kind: Pod
metadata:
    labels:
        app: radiofeed-pod
    name: radiofeed-pod
spec:
    containers:
        - name: mailpit
          image: docker.io/axllent/mailpit:v1.17
          ports:
              - containerPort: 1025
                hostPort: 1025
              - containerPort: 8025
                hostPort: 8025
        - name: redis
          image: docker.io/library/redis:7.2-bookworm
          ports:
              - containerPort: 6379
                hostPort: 6379
        - name: postgres
          env:
              - name: POSTGRES_PASSWORD
                value: password
          image: docker.io/library/postgres:16.2-bookworm
          ports:
              - containerPort: 5432
                hostPort: 5432
          volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: pg_data-pvc
    volumes:
        - name: pg_data-pvc
          persistentVolumeClaim:
              claimName: radiofeed_pg_data
