# Generated by Django 3.2.3 on 2021-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="cover_image_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="cover_image_etag",
            field=models.TextField(blank=True),
        ),
    ]
