# Generated by Django 3.2.5 on 2021-07-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0017_rename_creators_podcast_owner"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;"
            "CREATE TRIGGER podcast_update_search_trigger "
            "BEFORE INSERT OR UPDATE OF title, keywords, owner, extracted_text, search_vector "
            "ON podcasts_podcast "
            "FOR EACH ROW EXECUTE PROCEDURE "
            "tsvector_update_trigger("
            "search_vector, 'pg_catalog.english', title, keywords, owner, extracted_text);"
            "UPDATE podcasts_podcast SET search_vector = NULL;",
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;",
        ),
    ]
