# Generated by Django 3.2.5 on 2021-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0022_podcast_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
