# Generated by Django 3.2.6 on 2021-08-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0029_auto_20210808_0700"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="status",
        ),
        migrations.AddField(
            model_name="podcast",
            name="result",
            field=models.JSONField(default=dict),
        ),
    ]
