# Generated by Django 3.2.7 on 2021-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0043_alter_podcast_hub_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
