# Generated by Django 3.2.7 on 2021-09-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0049_podcast_websub_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="num_episodes",
        ),
    ]
