# Generated by Django 3.2.8 on 2021-10-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0061_remove_podcast_succeeded"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_changed_2e38d6_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="changed",
        ),
    ]
