# Generated by Django 3.2.8 on 2021-10-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0066_auto_20211014_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
