# Generated by Django 3.2.8 on 2021-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0069_auto_20211016_0639"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="indexed",
            field=models.BooleanField(default=False),
        ),
    ]
