# Generated by Django 3.2.8 on 2021-10-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0070_podcast_indexed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="indexed",
        ),
    ]
