# Generated by Django 3.2.8 on 2021-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0077_alter_podcast_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
