#!/bin/sh

set -o errexit
set -o nounset

# initial frontend build
npm run watch-js
npm run watch-css

# watch frontend file changes
watchman watch /app/static/src/js

watchman -j <<-EOT
["trigger", "/app/static/src/js", {
   "name": "esbuild",
   "expression": ["match", "**/*.js", "wholename"],
   "command": ["npm", "run", "watch-js"],
   "append_files": false
}]
EOT


watchman watch /app/static/src/css

watchman -j <<-EOT
["trigger", "/app/static/src/css", {
   "name": "tailwind-css",
   "expression": ["match", "**/*.css", "wholename"],
   "command": ["npm", "run", "watch-css"],
   "append_files": false
}]
EOT


watchman watch /app/templates

watchman -j <<-EOT
["trigger", "/app/templates", {
   "name": "tailwind-html",
   "expression": ["match", "**/*.html", "wholename"],
   "command": ["npm", "run", "watch-css"],
   "append_files": false
}]
EOT

# start django
./manage.py migrate
./manage.py runserver 0.0.0.0:8000
