# Generated by Django 5.1.5 on 2025-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0005_alter_episode_episode_type"),
        ("podcasts", "0013_podcast_podcast_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "season"], name="episodes_ep_podcast_965d74_idx"
            ),
        ),
    ]
