# Generated by Django 5.1.6 on 2025-02-25 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0006_episode_episodes_ep_podcast_965d74_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="length",
            new_name="file_size",
        ),
    ]
