# Generated by Django 5.2 on 2025-04-03 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0012_alter_episode_cover_url_alter_episode_media_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="cover_url",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="media_url",
            field=models.URLField(
                max_length=2083,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="website",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
