# Generated by Django 5.2.8 on 2025-11-23 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0026_remove_episode_episodes_ep_podcast_965d74_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audiolog",
            name="episodes_au_listene_7f0fdd_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiolog",
            name="episodes_au_listene_e5a9d5_idx",
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["user", "episode"], name="episodes_au_user_id_fef2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["user", "episode", "listened"],
                name="episodes_au_user_id_fb8578_idx",
            ),
        ),
    ]
