# Generated by Django 5.2.8 on 2025-11-23 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0027_remove_audiolog_episodes_au_listene_7f0fdd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookmark",
            name="episodes_bo_created_d69e08_idx",
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "episode"], name="episodes_bo_user_id_09cdb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "episode", "created"],
                name="episodes_bo_user_id_21f9c3_idx",
            ),
        ),
    ]
