# Generated by Django 5.2.8 on 2025-11-24 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0028_remove_bookmark_episodes_bo_created_d69e08_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audiolog",
            name="episodes_au_user_id_fb8578_idx",
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["user", "listened"],
                include=("episode_id",),
                name="episodes_audiolog_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["user", "-listened"],
                include=("episode_id",),
                name="episodes_audiolog_asc_idx",
            ),
        ),
    ]
