# Generated by Django 3.1.7 on 2021-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0011_auto_20210305_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="length",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
