# Generated by Django 3.2 on 2021-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0013_alter_queueitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
