# Generated by Django 3.2 on 2021-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0014_auto_20210413_1707"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
    ]
