# Generated by Django 3.2 on 2021-04-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0015_audiolog_is_playing"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="playback_rate",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
