# Generated by Django 3.2 on 2021-04-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0016_audiolog_playback_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiolog",
            name="is_playing",
        ),
        migrations.RemoveField(
            model_name="audiolog",
            name="playback_rate",
        ),
    ]
