# Generated by Django 4.0.4 on 2022-05-07 11:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Radiofeed', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='admin@localhost', max_length=254)),
                ('host_country', django_countries.fields.CountryField(default='FI', max_length=2)),
                ('age_of_consent', models.PositiveSmallIntegerField(default=18)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
