# Generated by Django 3.2.5 on 2021-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0002_auto_20210710_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="cover_url",
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
