# Generated by Django 3.2.6 on 2021-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0004_auto_20210802_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="episode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="season",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
