# Generated by Django 3.2.6 on 2021-08-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0013_audiolog_unique_episodes_audiolog_is_playing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiolog",
            name="autoplay",
        ),
    ]
