# Generated by Django 4.0.4 on 2022-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0024_delete_queueitem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="audiolog",
            name="unique_episodes_audiolog",
        ),
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="unique_episodes_bookmark",
        ),
        migrations.RemoveConstraint(
            model_name="episode",
            name="unique_episodes_episode",
        ),
        migrations.AddConstraint(
            model_name="audiolog",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="unique_episodes_audiolog_user_episode"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="unique_episodes_bookmark_user_episode"
            ),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(
                fields=("podcast", "guid"), name="unique_episodes_episode_podcast_guid"
            ),
        ),
    ]
