- name: Create .kube directory with read/write permissions on user home dir
  ansible.builtin.file:
      path: /home/{{ deploy_user }}/.kube
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: "u+rw"
      state: directory

- name: Copy kubeconfig to user home dir
  ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: "{{ kubeconfig }}"
      remote_src: true
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: "u+rw"

- name: Add KUBECONFIG environment variable to .bashrc and .profile
  lineinfile:
    path: "/home/{{ deploy_user }}/{{ item }}"
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG={{ kubeconfig }}'
    create: yes
    state: present
  loop:
    - .bashrc
    - .profile

- name: Reload shell configuration for the user
  shell: "bash -c 'source /home/{{ deploy_user }}/{{ item }}'"
  loop:
    - .bashrc
    - .profile
