# Generated by Django 3.1.3 on 2020-12-05 23:28

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("media_url", models.URLField(max_length=500)),
                ("media_type", models.CharField(max_length=20)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=12)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast"], name="episodes_ep_podcast_3361d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(fields=["guid"], name="episodes_ep_guid_b00554_idx"),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["-pub_date"], name="episodes_ep_pub_dat_205e36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["pub_date"], name="episodes_ep_pub_dat_60d1c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(fields=["title"], name="episodes_ep_title_4a6059_idx"),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(fields=["-title"], name="episodes_ep_title_ce2893_idx"),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(
                fields=("podcast", "guid"), name="unique_episode"
            ),
        ),
    ]
