# Generated by Django 3.2.5 on 2021-07-10 07:45

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="link",
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="media_url",
            field=models.URLField(max_length=2083),
        ),
    ]
