# Generated by Django 5.0.4 on 2024-04-21 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0002_add_episode_search_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommended_episodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
