# Generated by Django 3.1.3 on 2020-12-13 14:48

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0002_auto_20201207_2206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="duration",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
