# Generated by Django 3.1.6 on 2021-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_queueitem"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="queueitem",
            index=models.Index(
                fields=["position"], name="episodes_qu_positio_58d480_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="queueitem",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="uniq_queue_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="queueitem",
            constraint=models.UniqueConstraint(
                fields=("user", "position"), name="uniq_queue_item_position"
            ),
        ),
    ]
