# Generated by Django 3.1.3 on 2020-12-13 22:02

# Django
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_auto_20201213_1448"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="episode", name="episodes_ep_title_4a6059_idx",
        ),
        migrations.RemoveIndex(
            model_name="episode", name="episodes_ep_title_ce2893_idx",
        ),
        migrations.AddField(
            model_name="episode",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="episodes_ep_search__466ef4_gin"
            ),
        ),
    ]
