# Generated by Django 5.1.5 on 2025-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0004_remove_audiolog_created_remove_audiolog_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="episode_type",
            field=models.CharField(
                choices=[
                    ("full", "Full episode"),
                    ("trailer", "Trailer"),
                    ("bonus", "Bonus"),
                ],
                default="full",
                max_length=12,
            ),
        ),
    ]
