# Generated by Django 3.1.6 on 2021-02-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0004_auto_20210206_1207"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="queueitem",
            name="uniq_queue_item_position",
        ),
    ]
