# Generated by Django 3.1.3 on 2020-12-14 08:52

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0005_episode_search_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="media_type",
            field=models.CharField(max_length=60),
        ),
    ]
