# Generated by Django 3.1.3 on 2020-12-14 00:18

# Django
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Third Party Libraries
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("episodes", "0005_episode_search_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("current_time", models.PositiveIntegerField(default=0)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="episodes.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="playhistory",
            index=models.Index(
                fields=["-created"], name="episodes_pl_created_f7d73d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playhistory",
            index=models.Index(
                fields=["-modified"], name="episodes_pl_modifie_6c43b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playhistory",
            index=models.Index(
                fields=["-completed"], name="episodes_pl_complet_d2bba8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="uniq_play_history"
            ),
        ),
    ]
