# Generated by Django 3.1.6 on 2021-02-06 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("episodes", "0005_auto_20210206_1448"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookmark",
            new_name="Favorite",
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="uniq_bookmark",
        ),
        migrations.RemoveIndex(
            model_name="favorite",
            name="episodes_bo_created_d69e08_idx",
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["-created"], name="episodes_fa_created_edc79e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="uniq_favorite"
            ),
        ),
    ]
