# Generated by Django 3.2.6 on 2021-08-04 19:27

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0005_auto_20210803_1349"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["-pub_date", "-id"], name="episodes_ep_pub_dat_9b17cd_idx"
            ),
        ),
    ]
