# Generated by Django 3.1.6 on 2021-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0006_auto_20210206_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
