# Generated by Django 3.2.6 on 2021-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0006_episode_episodes_ep_pub_dat_9b17cd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="autoplay",
            field=models.BooleanField(default=False),
        ),
    ]
