# Generated by Django 3.2.6 on 2021-08-07 09:14

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0007_audiolog_autoplay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiolog",
            name="autoplay",
        ),
    ]
