# Generated by Django 3.1.3 on 2020-12-14 23:27

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0007_auto_20201214_2307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
