# Generated by Django 5.1.6 on 2025-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0007_rename_length_episode_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="File size in bytes"
            ),
        ),
    ]
