# Generated by Django 3.1.6 on 2021-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0008_auto_20210210_1702"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "pub_date"], name="episodes_ep_podcast_a7abe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "-pub_date"], name="episodes_ep_podcast_b9a49e_idx"
            ),
        ),
    ]
