# Generated by Django 3.2.6 on 2021-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0008_remove_audiolog_autoplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="autoplay",
            field=models.BooleanField(default=False),
        ),
    ]
