# Generated by Django 3.1.3 on 2020-12-16 08:54

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0008_auto_20201214_2327"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="history", name="episodes_hi_complet_ebe4aa_idx",
        ),
        migrations.RemoveField(model_name="history", name="completed",),
    ]
