# Generated by Django 3.1.3 on 2020-12-16 12:54

# Django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("episodes", "0009_auto_20201216_0854"),
    ]

    operations = [
        migrations.RenameModel(old_name="History", new_name="AudioLog",),
        migrations.RemoveConstraint(model_name="audiolog", name="uniq_history",),
        migrations.RemoveIndex(
            model_name="audiolog", name="episodes_hi_updated_29f4e9_idx",
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["-updated"], name="episodes_au_updated_eb4a9e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="audiolog",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="uniq_audio_log"
            ),
        ),
    ]
