# Generated by Django 3.2.6 on 2021-08-08 06:57

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0009_audiolog_autoplay"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="audiolog",
            name="uniq_audio_log",
        ),
        migrations.RemoveConstraint(
            model_name="episode",
            name="unique_episode",
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="uniq_favorite",
        ),
        migrations.AddConstraint(
            model_name="audiolog",
            constraint=models.UniqueConstraint(fields=("user", "episode"), name="unique_episodes_audiolog"),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(fields=("podcast", "guid"), name="unique_episodes_episode"),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(fields=("user", "episode"), name="unique_episodes_favorite"),
        ),
    ]
