# Generated by Django 3.1.6 on 2021-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0009_auto_20210211_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="episode",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
