# Generated by Django 3.1.7 on 2021-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0010_auto_20210219_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="media_url",
            field=models.URLField(max_length=1000),
        ),
    ]
