# Generated by Django 5.1.7 on 2025-03-23 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0010_remove_episode_episodes_ep_episode_c8cf94_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_podcast_3361d9_idx",
        ),
    ]
