# Generated by Django 5.2 on 2025-04-03 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0011_remove_episode_episodes_ep_podcast_3361d9_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="cover_url",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="media_url",
            field=models.URLField(
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="website",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
    ]
