# Generated by Django 3.2.6 on 2021-08-08 07:03

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0011_auto_20210808_0701"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
    ]
