# Generated by Django 3.2.6 on 2021-08-08 07:53

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0012_audiolog_is_playing"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="audiolog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_playing", True)),
                fields=("user", "is_playing"),
                name="unique_episodes_audiolog_is_playing",
            ),
        ),
    ]
