# Generated by Django 5.2.6 on 2025-09-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0013_alter_episode_cover_url_alter_episode_media_url_and_more"),
        ("podcasts", "0045_remove_podcast_podcasts_po_itunes__d69e24_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_podcast_a7abe0_idx",
        ),
        migrations.RemoveIndex(
            model_name="episode",
            name="episodes_ep_podcast_b9a49e_idx",
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "pub_date", "id"],
                name="episodes_ep_podcast_12cd3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "-pub_date", "-id"],
                name="episodes_ep_podcast_c43bb8_idx",
            ),
        ),
    ]
