# Generated by Django 3.2.6 on 2021-08-08 12:55

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0014_remove_audiolog_autoplay"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="audiolog",
            name="unique_episodes_audiolog_is_playing",
        ),
        migrations.RemoveField(
            model_name="audiolog",
            name="is_playing",
        ),
    ]
