# Generated by Django 5.2.6 on 2025-09-12 22:16

from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations, models

timeout_statement = "SET statement_timeout = 0;"


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("episodes", "0014_remove_episode_episodes_ep_podcast_a7abe0_idx_and_more"),
        ("podcasts", "0045_remove_podcast_podcasts_po_itunes__d69e24_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(timeout_statement, reverse_sql=timeout_statement),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_pub_dat_60d1c1_idx",
        ),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_pub_dat_205e36_idx",
        ),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["pub_date", "id"], name="episodes_ep_pub_dat_866539_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["-pub_date", "-id"], name="episodes_ep_pub_dat_9b17cd_idx"
            ),
        ),
    ]
