# Generated by Django 3.2.6 on 2021-08-12 05:14

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0015_auto_20210808_1255"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(fields=["updated"], name="episodes_au_updated_033e45_idx"),
        ),
    ]
