# Generated by Django 5.2.7 on 2025-10-04 11:17

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

timeout_statement = "SET statement_timeout = 0;"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("episodes", "0016_remove_episode_episodes_ep_podcast_12cd3c_idx_and_more"),
        ("podcasts", "0045_remove_podcast_podcasts_po_itunes__d69e24_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(timeout_statement, reverse_sql=timeout_statement),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "-pub_date", "-id"],
                name="episodes_ep_podcast_c43bb8_idx",
            ),
        ),
    ]
