# Generated by Django 3.2.6 on 2021-08-20 19:23

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0016_audiolog_episodes_au_updated_033e45_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="link",
        ),
    ]
