# Generated by Django 3.2.6 on 2021-08-27 09:00

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0017_remove_episode_link"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;"
            "CREATE TRIGGER episode_update_search_trigger "
            "BEFORE INSERT OR UPDATE OF title, search_vector ON episodes_episode "
            "FOR EACH ROW EXECUTE PROCEDURE "
            "tsvector_update_trigger(search_vector, 'pg_catalog.english', title);"
            "UPDATE episodes_episode SET search_vector = NULL;",
            reverse_sql="DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;",
        ),
    ]
