# Generated by Django 5.2.7 on 2025-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0017_episode_episodes_ep_podcast_c43bb8_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
