# Generated by Django 5.2.7 on 2025-10-07 18:47

from django.db import migrations


def duration_in_seconds(duration_str) -> int:
    """Returns total number of seconds given string in [h:][m:]s format."""
    if not duration_str:
        return 0

    try:
        return sum(
            (int(part) * multiplier)
            for (part, multiplier) in zip(
                reversed(duration_str.split(":")[:3]),
                (1, 60, 3600),
                strict=False,
            )
        )
    except ValueError:
        return 0


def set_default_audio_log_duration(apps, schema_editor):
    AudioLog = apps.get_model("episodes", "AudioLog")
    for_update = []

    for audio_log in AudioLog.objects.filter(
        duration=0,
        episode__duration__isnull=False,
    ).select_related("episode"):
        audio_log.duration = duration_in_seconds(audio_log.episode.duration)
        for_update.append(audio_log)

    AudioLog.objects.bulk_update(for_update, ["duration"])


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0018_audiolog_duration"),
    ]

    operations = [
        migrations.RunPython(
            set_default_audio_log_duration,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
