# Generated by Django 3.2.7 on 2021-09-21 11:29

import django.db.models.expressions

from django.db import migrations, models


def reset_all_logs(apps, schema_editor):
    apps.get_model("episodes", "AudioLog").objects.update(is_playing=False)


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0019_audiolog_is_playing"),
    ]

    operations = [
        migrations.RunPython(
            reset_all_logs,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="audiolog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_playing", True),
                    ("user", django.db.models.expressions.F("user")),
                ),
                fields=("user", "is_playing"),
                name="unique_episodes_audiolog_is_playing",
            ),
        ),
    ]
