# Generated by Django 5.2.8 on 2025-11-18 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0019_set_default_audio_log_duration"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = 0;",
            reverse_sql="SET statement_timeout = 0;",
        ),
        migrations.RunSQL(
            sql="""
DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;
CREATE TRIGGER episode_update_search_trigger
BEFORE INSERT OR UPDATE OF title, search_vector
ON episodes_episode
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(search_vector, 'pg_catalog.english', title);
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;
CREATE TRIGGER episode_update_search_trigger
BEFORE INSERT OR UPDATE OF title, search_vector
ON episodes_episode
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(search_vector, 'pg_catalog.english', title, keywords);
            """,
        ),
        migrations.RemoveField(
            model_name="episode",
            name="keywords",
        ),
    ]
