# Generated by Django 3.2.7 on 2021-09-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0020_audiolog_unique_episodes_audiolog_is_playing"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="audiolog",
            name="unique_episodes_audiolog_is_playing",
        ),
        migrations.RemoveField(
            model_name="audiolog",
            name="is_playing",
        ),
    ]
