# Generated by Django 5.2.8 on 2025-11-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0020_remove_episode_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="keywords",
            field=models.TextField(blank=True),
        ),
    ]
