# Generated by Django 5.2.8 on 2025-11-18 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0021_episode_keywords"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;
CREATE TRIGGER episode_update_search_trigger
BEFORE INSERT OR UPDATE OF title, keywords, search_vector
ON episodes_episode
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(search_vector, 'pg_catalog.english', title, keywords);
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;
CREATE TRIGGER episode_update_search_trigger
BEFORE INSERT OR UPDATE OF title, search_vector
ON episodes_episode
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(search_vector, 'pg_catalog.english', title);
            """,
        ),
    ]
