# Generated by Django 4.0 on 2021-12-22 11:52

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0023_rename_favorite_bookmark_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueueItem",
        ),
    ]
