# Generated by Django 5.2.8 on 2025-11-23 13:27

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


def ensure_episodes_loaded(apps, schema_editor):
    """
    Forces Django to fully register the 'episodes' app in the historical registry.
    This prevents LookupError in later migrations that reference Episode.
    """
    apps.get_app_config("episodes")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("episodes", "0023_update_episode_search_trigger_with_simple"),
    ]

    operations = [
        migrations.RunPython(
            ensure_episodes_loaded,
            reverse_code=migrations.RunPython.noop,
        ),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_pub_dat_4abe4c_idx",
        ),
    ]
