# Generated by Django 5.2.8 on 2025-11-23 13:41

from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations, models

timeout_statement = "SET statement_timeout = 0;"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("episodes", "0024_remove_episode_episodes_ep_pub_dat_4abe4c_idx"),
        ("podcasts", "0065_remove_podcast_podcasts_po_pub_dat_2e433a_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(timeout_statement, reverse_sql=timeout_statement),
        RemoveIndexConcurrently(
            model_name="episode",
            name="episodes_ep_pub_dat_34887e_idx",
        ),
        AddIndexConcurrently(
            model_name="episode",
            index=models.Index(
                fields=["podcast", "pub_date", "id"],
                name="episodes_ep_podcast_12cd3c_idx",
            ),
        ),
    ]
