# Generated by Django 4.0.4 on 2022-05-16 06:46

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0025_remove_audiolog_unique_episodes_audiolog_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audiolog",
            name="episodes_au_updated_eb4a9e_idx",
        ),
        migrations.RemoveIndex(
            model_name="audiolog",
            name="episodes_au_updated_033e45_idx",
        ),
        migrations.RenameField(
            model_name="audiolog",
            old_name="updated",
            new_name="listened",
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["-listened"], name="episodes_au_listene_7f0fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiolog",
            index=models.Index(
                fields=["listened"], name="episodes_au_listene_e5a9d5_idx"
            ),
        ),
    ]
