# Generated by Django 4.1.3 on 2022-11-03 21:19


import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcasts", "0009_alter_category_name_alter_category_name_en_and_more"),
        ("episodes", "0029_alter_audiolog_episode_alter_audiolog_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolog",
            name="current_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="audiolog",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_logs",
                to="episodes.episode",
            ),
        ),
        migrations.AlterField(
            model_name="audiolog",
            name="listened",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="audiolog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="episodes.episode",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="cover_url",
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="duration",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="episode",
            name="episode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="episode_type",
            field=models.CharField(default="full", max_length=30),
        ),
        migrations.AlterField(
            model_name="episode",
            name="explicit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="episode",
            name="guid",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="episode",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="length",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="link",
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="media_type",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="episode",
            name="media_url",
            field=models.URLField(max_length=2083),
        ),
        migrations.AlterField(
            model_name="episode",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="podcasts.podcast",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="pub_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="episode",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="season",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
