# Generated by Django 5.2.8 on 2025-11-24 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0029_remove_audiolog_episodes_au_user_id_fb8578_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookmark",
            name="episodes_bo_user_id_21f9c3_idx",
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "created"],
                include=("episode_id",),
                name="episodes_bookmark_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created"],
                include=("episode_id",),
                name="episodes_bookmark_asc_idx",
            ),
        ),
    ]
