# Generated by Django 5.2.8 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0030_remove_bookmark_episodes_bo_user_id_21f9c3_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolog",
            name="current_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="audiolog",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
