# Generated by Django 4.1.7 on 2023-03-04 09:19


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "episodes",
            "0030_alter_audiolog_current_time_alter_audiolog_episode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
    ]
