# Generated by Django 4.2.2 on 2023-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "episodes",
            "0033_remove_audiolog_unique_episodes_audiolog_is_playing_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="link",
            new_name="website",
        ),
    ]
