#!/bin/sh

set -o errexit
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

from urllib.parse import urlparse

db_url = urlparse("${DATABASE_URL}")

try:
    psycopg2.connect(
        dbname=db_url.path[1:],
        user=db_url.username,
        password=db_url.password,
        host=db_url.hostname,
        port=db_url.port,
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
