# Deployment settings

docker_image: "ghcr.io/danjac/radiofeed-app:main"

postgres:
  image: "postgres:16.6-bookworm"
  password: "{{ postgres_password }}"
  volume: "{{ postgres_volume | default('/home/ubuntu/pg_data', true) }}"

redis:
  image: "redis:8.2.2-bookworm"

# Cron job schedules

cron_schedules_default:
  clear_sessions: "20 5 * * *" # 5:20 AM every day
  create_recommendations: "20 4 * * *" # 4:20 AM every day
  fetch_top_itunes: "15 3 * * *" # 3:15 AM every day
  parse_feeds: "*/6 * * * *" # Every 6 minutes
  send_notifications: "0 16 * * 1" # 4:00 PM every Monday
  send_recommendations: "0 16 * * 5" # 4:00 PM every Friday

# Django settings

admin_site_header: "Radiofeed Admin [Production]"
admin_url: "admin/"
admins: "admin@{{ domain }}"
allowed_hosts: "*"
contact_email: "contact@{{ domain }}"
conn_pool_max_idle: 120
conn_pool_max_lifetime: 1800
conn_pool_max_size: 100
conn_pool_max_waiting: 25
conn_pool_min_size: 2
conn_pool_timeout: 20
csp_script_whitelist: "*.account.google.com,*.googleapis.com,*.cloudflareinsights.com"
itunes_chart_country: "gb"
mailgun_api_key: ""
mailgun_api_url: "https://api.eu.mailgun.net/v3"
mailgun_sender_domain: "mg.{{ domain }}"
meta_author: "Site owner"
meta_copyright: "{{ meta_author }} {{ ansible_date_time.year }}"
meta_description: "Podcast aggregator site"
meta_keywords: "podcasts, feeds, rss"
pwa_sha256_fingerprints: ""
secret_key_fallbacks: ""
secure_ssl_redirect: false
sentry_url: ""
