# Generated by Django 3.1.3 on 2020-12-22 10:01

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="autoplay",
            field=models.BooleanField(default=False),
        ),
    ]
