# Generated by Django 3.1.3 on 2020-12-22 10:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_autoplay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="send_recommendations_email",
            field=models.BooleanField(default=True),
        ),
    ]
