# Generated by Django 3.2.5 on 2021-07-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0020_rename_last_checked_podcast_scheduled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
