# Generated by Django 3.2.7 on 2021-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0041_podcast_hub_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="hub_exception",
            field=models.TextField(blank=True),
        ),
    ]
