# Generated by Django 3.2.7 on 2021-09-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0045_auto_20210918_2018"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="subscribed",
            new_name="websub_subscribed",
        ),
        migrations.RenameField(
            model_name="podcast",
            old_name="requested",
            new_name="websub_requested",
        ),
        migrations.RenameField(
            model_name="podcast",
            old_name="hub_token",
            new_name="websub_token",
        ),
        migrations.RenameField(
            model_name="podcast",
            old_name="hub",
            new_name="websub_hub",
        ),
        migrations.RenameField(
            model_name="podcast",
            old_name="hub_exception",
            new_name="websub_exception",
        ),
    ]
