# Generated by Django 3.2.8 on 2021-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0077_alter_podcast_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="frequency_modifier",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="podcast",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
