# Generated by Django 3.2.8 on 2021-10-27 19:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0078_auto_20211027_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
