# Generated by Django 3.2.8 on 2021-10-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0079_alter_podcast_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="frequency_modifier",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
