# Generated by Django 3.2.8 on 2021-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0080_auto_20211027_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='frequency',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
