# Generated by Django 3.2.8 on 2021-11-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0081_auto_20211030_1330"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
