# Generated by Django 3.2.9 on 2021-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0085_podcast_subscribe_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="last_subscribe_callback",
        ),
        migrations.AlterField(
            model_name="podcast",
            name="subscribe_status",
            field=models.CharField(
                choices=[
                    ("unsubscribed", "Unsubscribed"),
                    ("requested", "Requested"),
                    ("subscribed", "Subscribed"),
                    ("denied", "Denied"),
                    ("error", "Error"),
                ],
                default="unsubscribed",
                max_length=30,
            ),
        ),
    ]
