# Generated by Django 3.2.9 on 2021-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0089_auto_20211116_0700"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
