# Generated by Django 3.2.9 on 2021-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0092_auto_20211116_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_exception",
            field=models.TextField(blank=True),
        ),
    ]
