# Generated by Django 3.2.9 on 2021-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0095_auto_20211117_0830"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podcastindex",
            field=models.BooleanField(default=False),
        ),
    ]
