# Generated by Django 3.2.9 on 2021-11-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0096_podcast_podcastindex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="schedule_modifier",
            new_name="frequency_modifier",
        ),
    ]
