# Generated by Django 3.2.9 on 2021-12-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0111_podcast_podping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_exception",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_hub",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_mode",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_secret",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_status",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_status_changed",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_timeout",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_token",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_url",
        ),
    ]
