# Generated by Django 4.0 on 2022-01-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0120_rename_follow_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_podcast_title_lower",
        ),
    ]
