# Generated by Django 4.0.4 on 2022-05-07 15:45

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Radiofeed', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('site_owner', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(default='admin@localhost', max_length=254)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('host_country', django_countries.fields.CountryField(default='FI', max_length=2)),
                ('age_of_consent', models.PositiveSmallIntegerField(default=18)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
