# Generated by Django 3.2.5 on 2021-07-03 06:57


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="autoplay",
            field=models.BooleanField(default=True),
        ),
    ]
