# Generated by Django 4.0 on 2021-12-23 07:05


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_autoplay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="autoplay",
        ),
    ]
