# Generated by Django 4.1.3 on 2022-11-03 21:19


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "Suomi")], default="en", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="send_email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
