# Generated by Django 3.1.3 on 2020-12-21 01:05

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_podcast_search_trigger_with_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
