# Generated by Django 3.2.3 on 2021-06-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0008_podcast_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
