# Generated by Django 3.2.3 on 2021-06-01 17:19

from django.db import migrations
from django.db.models import F


def set_last_checked(apps, schema_editor):
    model = apps.get_model("podcasts", "Podcast")
    model.objects.update(last_checked=F("last_updated"))


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_podcast_last_checked"),
    ]

    operations = [
        migrations.RunPython(set_last_checked, reverse_code=migrations.RunPython.noop)
    ]
