# Generated by Django 3.1.5 on 2021-01-28 12:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0010_podcast_num_retries"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
