# Generated by Django 3.2.4 on 2021-06-12 12:52

from django.db import migrations


def set_modified_to_none(apps, schema_editor):
    model = apps.get_model("podcasts.Podcast")
    model.objects.update(modified=None)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0010_podcast_updated"),
    ]

    operations = [
        migrations.RunPython(
            set_modified_to_none, reverse_code=migrations.RunPython.noop
        )
    ]
