# Generated by Django 3.1.6 on 2021-02-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0011_podcast_promoted"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            CREATE TRIGGER podcast_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, keywords, authors, extracted_text, search_vector
            ON podcasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector,
              'pg_catalog.english',
              title,
              keywords,
              authors,
              extracted_text);
            UPDATE podcasts_podcast SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            """,
        )
    ]
