# Generated by Django 3.2.4 on 2021-06-13 07:27

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0012_podcast_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="error_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="podcasts.podcast",
            ),
        ),
    ]
