# Generated by Django 3.1.7 on 2021-03-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0017_podcast_cover_image_etag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="cover_image_etag",
        ),
    ]
