# Generated by Django 3.1.7 on 2021-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0019_auto_20210310_1029"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="uniq_subscription",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "podcast"), name="uniq_follow"
            ),
        ),
    ]
