# Generated by Django 3.1.7 on 2021-03-12 10:33

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0020_auto_20210310_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
