# Generated by Django 3.1.7 on 2021-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0021_podcast_created"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-created", "-pub_date"], name="podcasts_po_created_47ec2f_idx"
            ),
        ),
    ]
