# Generated by Django 3.1.7 on 2021-03-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0024_auto_20210320_2156"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            CREATE TRIGGER podcast_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, creators, search_vector
            ON podcasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector,
              'pg_catalog.english',
              title,
              creators);
            UPDATE podcasts_podcast SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            """,
        )
    ]
