# Generated by Django 3.2 on 2021-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0025_add_creators_to_search_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
