# Generated by Django 3.2 on 2021-04-21 10:46

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0027_auto_20210413_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="language",
            field=models.CharField(
                default="en",
                max_length=2,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
