# Generated by Django 5.1.4 on 2025-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0008_recommendation_score"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendation",
            name="podcasts_re_similar_3e4170_idx",
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["-score"], name="podcasts_re_score_c89df8_idx"),
        ),
    ]
