# Generated by Django 5.1.7 on 2025-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0021_clear_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="parser_error",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate", "Duplicate"),
                    ("discontinued", "Discontinued"),
                    ("invalid_data", "Invalid Data"),
                    ("invalid_rss", "Invalid RSS"),
                    ("not_modified", "Not Modified"),
                    ("unavailable", "Unavailable"),
                    ("inaccessible", "Inaccessible"),
                ],
                max_length=30,
            ),
        ),
    ]
