# Generated by Django 5.1.7 on 2025-03-15 12:02

from django.db import migrations


def _mark_podcasts_complete(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    # all podcasts that are not active and have no parser error
    # can be assumed to be complete
    Podcast.objects.filter(
        complete=False,
        active=False,
        parser_error__isnull=True,
    ).update(complete=True)


def _unmark_podcasts_complete(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(complete=True).update(complete=False)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0025_podcast_complete"),
    ]

    operations = [
        migrations.RunPython(
            _mark_podcasts_complete,
            reverse_code=_unmark_podcasts_complete,
        )
    ]
