# Generated by Django 5.2 on 2025-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0031_alter_podcast_cover_url_alter_podcast_funding_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
