# Generated by Django 5.2.2 on 2025-06-07 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0039_podcast_podcasts_po_itunes__d69e24_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_fdc955_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="promoted",
        ),
    ]
