# Generated by Django 5.2.3 on 2025-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0042_podcast_podcasts_po_parser__9f31ab_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
