# Generated by Django 5.2.3 on 2025-06-18 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0044_promote_itunes_feeds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_itunes__d69e24_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="itunes_ranking",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["promoted"], name="podcasts_po_promote_fdc955_idx"
            ),
        ),
    ]
