# Generated by Django 5.2.8 on 2025-11-14 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0052_remove_podcast_podcasts_po_promote_fdc955_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_score_aeb891_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="score",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["promoted"], name="podcasts_po_promote_fdc955_idx"
            ),
        ),
    ]
