# Generated by Django 5.2.8 on 2025-11-17 16:15

from django.db import migrations
from django.utils.text import slugify


def set_podcast_slugs(apps, schema_editor):
    Category = apps.get_model("podcasts", "Category")
    to_update = []
    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            to_update.append(category)

    Category.objects.bulk_update(to_update, ["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0056_category_slug"),
    ]

    operations = [
        migrations.RunPython(
            set_podcast_slugs,
            migrations.RunPython.noop,
        )
    ]
