# Generated by Django 5.2.8 on 2025-11-23 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0064_remove_podcast_podcasts_po_promote_fdc955_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_pub_dat_2e433a_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_active_a4c988_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_parser__9f31ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_a89157_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["active", "-promoted", "parsed", "updated"],
                name="podcasts_po_active_b74445_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                condition=models.Q(("private", False), ("pub_date__isnull", False)),
                fields=["-pub_date"],
                name="podcasts_podcast_public_idx",
            ),
        ),
    ]
