# Generated by Django 6.0 on 2025-12-07 10:21

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0065_remove_podcast_podcasts_po_pub_dat_2e433a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                django.db.models.functions.text.Lower("owner"),
                name="podcasts_podcast_owner_idx",
            ),
        ),
    ]
