# Generated by Django 6.0 on 2025-12-07 10:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0066_podcast_podcasts_podcast_owner_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_podcast_owner_idx",
        ),
        migrations.AddField(
            model_name="podcast",
            name="owner_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["owner_search_vector"], name="podcasts_po_owner_s_734402_gin"
            ),
        ),
    ]
