# Generated by Django 6.0 on 2025-12-07 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0067_remove_podcast_podcasts_podcast_owner_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER podcast_update_owner_search_trigger
BEFORE INSERT OR UPDATE OF owner ON podcasts_podcast
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    owner_search_vector, 'pg_catalog.simple', owner
);
UPDATE podcasts_podcast SET owner = owner;""",
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_owner_search_trigger ON podcasts_podcast;",
        ),
    ]
