# Generated by Django 6.0 on 2025-12-07 12:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0068_create_owner_search_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="podcasts_ca_search__6e34c5_gin"
            ),
        ),
    ]
