# Generated by Django 6.0 on 2025-12-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0070_create_category_name_search_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
