# Generated by Django 6.0 on 2025-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0076_remove_podcast_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="promoted_at",
            field=models.BooleanField(default=False),
        ),
    ]
