# Generated by Django 6.0 on 2025-12-09 16:59

from django.db import migrations


def set_is_promoted(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(promoted__isnull=False).update(promoted_at=True)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0077_podcast_promoted_at"),
    ]

    operations = [
        migrations.RunPython(set_is_promoted, reverse_code=migrations.RunPython.noop)
    ]
