# Generated by Django 6.0 on 2025-12-09 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0078_set_default_is_promoted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_047f56_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_active_b74445_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-promoted_at", "language", "-pub_date"],
                name="podcasts_po_promote_ab9069_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["active", "-promoted_at", "parsed", "updated"],
                name="podcasts_po_active_aed488_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="promoted",
        ),
    ]
