# Generated by Django 6.0 on 2025-12-09 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0080_remove_podcast_podcasts_po_promote_ab9069_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="podcasts_ca_name_604e91_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="podcasts_ca_search__6e34c5_gin",
        ),
        migrations.RemoveField(
            model_name="category",
            name="search_vector",
        ),
    ]
