# Generated by Django 6.0 on 2025-12-17 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0083_remove_podcast_has_similar_podcasts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="num_retries",
        ),
    ]
