# Generated by Django 6.0 on 2025-12-19 16:13

import http

from django.db import migrations


def set_default_feed_status(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")

    podcasts = Podcast.objects.filter(feed_status="")

    # Any podcast with a canonical ID is "duplicate"

    podcasts.filter(canonical_id__isnull=False).update(feed_status="duplicate")

    # Any podcast with HTTP 304 status is "not_modified"

    podcasts.filter(http_status=http.HTTPStatus.NOT_MODIFIED).update(
        feed_status="not_modified"
    )

    # Any podcast with specific permanent HTTP error statuses is "permanent_http_error"
    podcasts.filter(
        http_status__in=(
            http.HTTPStatus.BAD_REQUEST,
            http.HTTPStatus.FORBIDDEN,
            http.HTTPStatus.METHOD_NOT_ALLOWED,
            http.HTTPStatus.NOT_ACCEPTABLE,
            http.HTTPStatus.NOT_FOUND,
            http.HTTPStatus.UNAUTHORIZED,
            http.HTTPStatus.UNAVAILABLE_FOR_LEGAL_REASONS,
        )
    ).update(feed_status="permanent_http_error")

    # Any podcast with HTTP 410 status is "discontinued"

    podcasts.filter(http_status=http.HTTPStatus.GONE).update(feed_status="discontinued")

    # Any podcast with not OK status (excluding the above) is "temporary_http_error"
    #
    podcasts.filter(http_status__isnull=False).exclude(
        http_status=http.HTTPStatus.OK
    ).update(feed_status="temporary_http_error")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0091_podcast_feed_status"),
    ]

    operations = [
        migrations.RunPython(
            set_default_feed_status,
            reverse_code=migrations.RunPython.noop,
        )
    ]
