#!/usr/bin/env bash

set -euo pipefail

echo "Building assets..."
docker-compose run --rm assets yarn build

echo "Deploying assets to S3..."
docker-compose run --rm \
    -e DJANGO_SETTINGS_MODULE=radiofeed.config.settings.deploy \
    django ./manage.py collectstatic --noinput -v 3 -i local

echo "Deploying to Heroku..."
git push heroku master
