#!/usr/bin/env bash

set -euo pipefail

echo "Running tests..."
docker-compose run --rm django pytest

echo "Building assets..."
docker-compose run --rm assets yarn build-js
docker-compose run --rm assets yarn build-css

echo "Deploying assets to S3..."
docker-compose run --rm \
    -e DJANGO_SETTINGS_MODULE=radiofeed.config.settings.deploy \
    django ./manage.py collectstatic --noinput -v 3 -i dev -i static/js -i static/css

echo "Deploying to Dokku..."
git push dokku main

