#!/usr/bin/env bash

set -o pipefail

if [[ ! -v JCASTS_SSH ]]; then
  echo "You must set $JCASTS_SSH environment variable to domain/IP of your Dokku server"
  exit 1
fi
if [[ ! -v JCASTS_APPNAME ]]; then
  JCASTS_APPNAME="jcasts"
fi

ssh "dokku@${JCASTS_SSH}" -t logs $JCASTS_APPNAME $@

