# Generated by Django 3.1.3 on 2020-12-06 23:44
# Django
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [TrigramExtension()]
