# Generated by Django 4.2.7 on 2023-11-01 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER podcast_update_search_trigger
BEFORE INSERT OR UPDATE OF title, owner, keywords, search_vector ON podcasts_podcast
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english', title, owner, keywords);
UPDATE podcasts_podcast SET search_vector = NULL;""",
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;",
        ),
    ]
