# Generated by Django 3.1.3 on 2020-12-16 18:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_squashed_0006_podcast_search_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="itunes_genre_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
