# Generated by Django 3.1.3 on 2020-12-17 21:26

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_category_itunes_genre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="itunes_genre_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="iTunes Genre ID"
            ),
        ),
    ]
