# Generated by Django 5.0.4 on 2024-05-04 09:27

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0003_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItunesSearch",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("search", models.CharField(max_length=200)),
                ("completed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ITunes search",
                "verbose_name_plural": "ITunes searches",
            },
        ),
    ]
