# Generated by Django 3.2.3 on 2021-05-29 09:00

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0004_remove_podcast_cover_image_etag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="cover_image_date",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="num_retries",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="sync_error",
        ),
    ]
