# Generated by Django 5.0.4 on 2024-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0004_itunessearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itunessearch",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
