# Generated by Django 3.1.3 on 2020-12-20 12:14

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0004_auto_20201219_1325"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            CREATE TRIGGER podcast_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, keywords, authors, search_vector
            ON podcasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.english', title, keywords, authors);
            UPDATE podcasts_podcast SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            """,
        )
    ]
