# Generated by Django 5.0.4 on 2024-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0005_alter_itunessearch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itunessearch",
            name="id",
            field=models.TextField(
                editable=False,
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="itunessearch",
            name="search",
            field=models.TextField(),
        ),
    ]
