# Generated by Django 3.2.3 on 2021-05-29 10:34

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0005_auto_20210529_0900"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;"
            "CREATE TRIGGER podcast_update_search_trigger "
            "BEFORE INSERT OR UPDATE OF title, keywords, creators, extracted_text, search_vector "
            "ON podcasts_podcast "
            "FOR EACH ROW EXECUTE PROCEDURE "
            "tsvector_update_trigger("
            "search_vector, 'pg_catalog.english', title, keywords, creators, extracted_text);"
            "UPDATE podcasts_podcast SET search_vector = NULL;",
            reverse_sql="DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;",
        ),
    ]
