# Generated by Django 4.1 on 2022-08-16 05:36


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0005_podcast_queued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
