# Generated by Django 3.1.3 on 2020-12-13 22:32

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0005_auto_20201213_2231"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER podcast_update_search_trigger
            BEFORE INSERT OR UPDATE OF title, keywords, search_vector
            ON podcasts_podcast
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.english', title, keywords);
            UPDATE podcasts_podcast SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS podcast_update_search_trigger
            ON podcasts_podcast;
            """,
        )
    ]
