# Generated by Django 5.1.1 on 2024-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "podcasts",
            "0005_alter_podcast_content_hash_alter_podcast_cover_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="modified",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
