# Generated by Django 4.1 on 2022-08-27 09:53


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcasts", "0006_remove_podcast_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="podcasts",
                to="podcasts.category",
                verbose_name="iTunes Categories",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="podcasts.podcast",
                verbose_name="Podcast",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subscriber",
            ),
        ),
    ]
