# Generated by Django 4.1 on 2022-08-27 10:11


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "podcasts",
            "0007_alter_podcast_categories_alter_subscription_podcast_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="podcasts.podcast",
                verbose_name="Podcast",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="recommended",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similar",
                to="podcasts.podcast",
                verbose_name="Similar Podcast",
            ),
        ),
    ]
