# Generated by Django 5.1.4 on 2025-01-02 09:51

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0007_alter_podcast_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="score",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("frequency"), "*", models.F("similarity")
                ),
                output_field=models.DecimalField(decimal_places=10, max_digits=100),
            ),
        ),
    ]
