# Generated by Django 3.2.3 on 2021-05-31 15:54

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0007_auto_20210531_0657"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
