# Generated by Django 3.2.4 on 2021-06-12 12:38

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0008_podcast_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="last_updated",
            new_name="modified",
        ),
    ]
