# Generated by Django 5.1.5 on 2025-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "podcasts",
            "0009_remove_recommendation_podcasts_re_similar_3e4170_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="itunes_ranking",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
