# Generated by Django 3.1.5 on 2021-01-23 10:09

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_podcast_sync_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_retries",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
