# Generated by Django 3.2.4 on 2021-06-12 12:47

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_rename_last_updated_podcast_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
