# Generated by Django 4.1.3 on 2022-12-03 09:32


import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0009_alter_category_name_alter_category_name_en_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                django.db.models.functions.text.Lower("title"),
                name="podcasts_podcast_lwr_title_idx",
            ),
        ),
    ]
