# Generated by Django 5.1.5 on 2025-01-15 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0011_podcast_podcasts_po_itunes__8b4558_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_itunes__8b4558_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="itunes_ranking",
        ),
    ]
