# Generated by Django 5.1.5 on 2025-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0012_remove_podcast_podcasts_po_itunes__8b4558_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podcast_type",
            field=models.CharField(
                choices=[("episodic", "Episodic"), ("serial", "Serial")],
                default="episodic",
                max_length=10,
            ),
        ),
    ]
