# Generated by Django 5.1.7 on 2025-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0013_podcast_podcast_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
