# Generated by Django 4.1.6 on 2023-02-09 08:15


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0014_remove_category_name_en_remove_category_name_fi"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_hub",
            field=models.URLField(blank=True, max_length=2086, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_secret",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_topic",
            field=models.URLField(blank=True, max_length=2086, null=True),
        ),
    ]
