# Generated by Django 3.2.5 on 2021-07-15 05:20

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0014_auto_20210710_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_episodes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
