# Generated by Django 5.1.7 on 2025-03-09 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0015_podcast_podcasts_po_rating_f96c31_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_fdc955_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="promoted",
        ),
    ]
