# Generated by Django 3.1.6 on 2021-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0015_remove_extracted_text_from_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
