# Generated by Django 3.2.5 on 2021-07-15 05:21

from __future__ import annotations

from django.db import migrations


def set_num_episodes(apps, schema_editor):
    podcast_model = apps.get_model("podcasts.Podcast")
    podcast_model.objects.filter(pub_date__isnull=False).update(num_episodes=1)


def reset_num_episodes(apps, schema_editor):
    podcast_model = apps.get_model("podcasts.Podcast")
    podcast_model.objects.update(num_episodes=0)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0015_podcast_num_episodes"),
    ]

    operations = [migrations.RunPython(set_num_episodes, reset_num_episodes)]
