# Generated by Django 4.1.6 on 2023-02-09 09:43


from django.db import migrations
from django.db.models import F


def set_default_verified(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(websub_expires__isnull=False).update(
        websub_verified=F("websub_requested")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0016_podcast_websub_verified"),
    ]

    operations = [
        migrations.RunPython(
            set_default_verified, reverse_code=migrations.RunPython.noop
        )
    ]
