# Generated by Django 5.1.7 on 2025-03-09 13:10

from django.db import migrations


def _set_default_promoted(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(rating__isnull=False).update(promoted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0017_podcast_promoted_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _set_default_promoted,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
