# Generated by Django 5.1.7 on 2025-03-10 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0018_set_default_promoted"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_rating_f96c31_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="rating",
        ),
    ]
