# Generated by Django 4.1.6 on 2023-02-09 19:34


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0018_remove_podcast_websub_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_verified",
        ),
    ]
