# Generated by Django 3.2.5 on 2021-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0018_update_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
