# Generated by Django 3.2.5 on 2021-07-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0019_podcast_last_checked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="last_checked",
            new_name="scheduled",
        ),
    ]
