# Generated by Django 4.1.6 on 2023-02-11 12:22


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0021_set_default_websub_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_content",
            field=models.TextField(blank=True),
        ),
    ]
