# Generated by Django 5.1.7 on 2025-03-15 11:40

from django.db import migrations


def _move_inaccessible_podcasts_to_unavailable(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")

    Podcast.objects.filter(parser_error="inaccessible").update(
        parser_error="unavailable"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0022_alter_podcast_parser_error"),
    ]

    operations = [
        migrations.RunPython(
            _move_inaccessible_podcasts_to_unavailable,
            reverse_code=migrations.RunPython.noop,
        )
    ]
