# Generated by Django 4.1.6 on 2023-02-11 14:37


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0022_podcast_websub_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_content",
        ),
    ]
