# Generated by Django 5.1.7 on 2025-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0023_move_inaccessible_podcasts_to_unavailable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="parser_error",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discontinued", "Discontinued"),
                    ("duplicate", "Duplicate"),
                    ("invalid_data", "Invalid Data"),
                    ("invalid_rss", "Invalid RSS"),
                    ("not_modified", "Not Modified"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=30,
            ),
        ),
    ]
