# Generated by Django 3.1.7 on 2021-03-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0023_remove_keywords_from_search"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="authors",
            new_name="creators",
        ),
    ]
