# Generated by Django 3.2.5 on 2021-07-30 22:08

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0025_remove_podcast_frequency"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_created_47ec2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_schedul_e9ba7e_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["scheduled", "-pub_date"], name="podcasts_po_schedul_e5e73a_idx"
            ),
        ),
    ]
