# Generated by Django 4.2.1 on 2023-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0025_remove_podcast_num_websub_retries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podping",
            field=models.BooleanField(default=False),
        ),
    ]
