# Generated by Django 5.1.7 on 2025-03-15 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0026_mark_podcasts_complete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(fields=["active"], name="podcasts_po_active_a4c988_idx"),
        ),
    ]
