# Generated by Django 3.2.5 on 2021-08-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0026_auto_20210730_2208"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="error_status",
            new_name="status",
        ),
    ]
