# Generated by Django 3.2.5 on 2021-08-02 09:42

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0027_rename_error_status_podcast_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="exception",
        ),
    ]
