# Generated by Django 5.1.7 on 2025-03-15 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0027_podcast_podcasts_po_active_a4c988_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="complete",
        ),
    ]
