# Generated by Django 5.2 on 2025-04-03 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "podcasts",
            "0029_remove_recommendation_podcasts_re_podcast_10c46d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="cover_url",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="funding_url",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="rss",
            field=models.URLField(
                max_length=500,
                unique=True,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="website",
            field=models.URLField(
                blank=True,
                max_length=2083,
                validators=[django.core.validators.URLValidator(["http", "https"])],
            ),
        ),
    ]
