# Generated by Django 4.2.1 on 2023-05-21 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0029_podcast_num_websub_retries_podcast_websub_expires_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="podping",
        ),
    ]
