# Generated by Django 3.2.6 on 2021-08-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0030_auto_20210812_0730"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="redirect_to",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="result",
        ),
    ]
