# Generated by Django 3.2.6 on 2021-08-19 05:30

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0031_auto_20210812_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="parsed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
