# Generated by Django 5.2 on 2025-04-11 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0032_podcast_queued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
