# Generated by Django 3.2.6 on 2021-08-19 05:30

from __future__ import annotations

from django.db import migrations
from django.db.models import F


def set_parsed(apps, schema_editor):
    podcast_model = apps.get_model("podcasts.Podcast")
    podcast_model.objects.filter(parsed__isnull=True).update(parsed=F("updated"))


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0032_podcast_parsed"),
    ]

    operations = [migrations.RunPython(set_parsed, migrations.RunPython.noop)]
