# Generated by Django 5.2 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0033_remove_podcast_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
