# Generated by Django 3.2.6 on 2021-08-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0033_set_parsed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="itunes_genre_id",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="itunes",
        ),
    ]
