# Generated by Django 4.2.1 on 2023-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0034_remove_podcast_parser_result_podcast_parser_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="immediate",
            field=models.BooleanField(
                default=False,
                help_text="Podcast feed should be queued for update immediately",
            ),
        ),
    ]
