# Generated by Django 4.2.1 on 2023-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0035_podcast_immediate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="immediate",
        ),
        migrations.AddField(
            model_name="podcast",
            name="queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
