# Generated by Django 5.2.1 on 2025-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "podcasts",
            "0035_remove_recommendation_podcasts_re_score_c89df8_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="similarity",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["-score"], name="podcasts_re_score_c89df8_idx"),
        ),
    ]
