# Generated by Django 4.2.1 on 2023-05-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0036_remove_podcast_immediate_podcast_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Only available to subscribers"
            ),
        ),
    ]
