# Generated by Django 5.2.2 on 2025-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0037_podcast_itunes_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="itunes_ranking",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
