# Generated by Django 4.2.1 on 2023-05-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0037_podcast_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podping",
            field=models.BooleanField(default=False),
        ),
    ]
