# Generated by Django 4.2.1 on 2023-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0038_podcast_podping"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_topic",
            field=models.URLField(blank=True, max_length=2086, null=True),
        ),
    ]
