# Generated by Django 3.2.7 on 2021-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0039_podcast_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="subscribed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
