# Generated by Django 4.2.1 on 2023-05-31 18:16

from django.db import migrations
from django.db.models import F


def set_websub_topic(apps, schema_editor):
    apps.get_model("podcasts", "Podcast").objects.filter(
        websub_hub__isnull=False,
        websub_topic__isnull=True,
    ).update(websub_topic=F("rss"))


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0039_podcast_websub_topic"),
    ]

    operations = [
        migrations.RunPython(set_websub_topic, reverse_code=migrations.RunPython.noop)
    ]
