# Generated by Django 3.2.7 on 2021-09-18 10:03

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0040_podcast_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="hub_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
