# Generated by Django 4.2.1 on 2023-06-04 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0040_set_webhub_topic_from_rss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="podping",
        ),
    ]
