# Generated by Django 4.2.1 on 2023-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0041_remove_podcast_podping"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="priority",
            field=models.BooleanField(default=False),
        ),
    ]
