# Generated by Django 5.2.3 on 2025-06-18 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0041_remove_podcast_parser_error_podcast_parser_result"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["parser_result"], name="podcasts_po_parser__9f31ab_idx"
            ),
        ),
    ]
