# Generated by Django 4.2.1 on 2023-06-04 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0042_podcast_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
