# Generated by Django 4.2.1 on 2023-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0043_remove_podcast_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
