# Generated by Django 5.2.3 on 2025-06-18 13:12

from django.db import migrations


def promote_feeds(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(itunes_ranking__isnull=False).update(promoted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0043_podcast_promoted"),
    ]

    operations = [migrations.RunPython(promote_feeds, migrations.RunPython.noop)]
