# Generated by Django 3.2.7 on 2021-09-18 20:18

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0044_podcast_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="hub",
            field=models.URLField(blank=True, null=True, verbose_name="WebSub URL"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="hub_exception",
            field=models.TextField(blank=True, verbose_name="WebSub exception"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="hub_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="WebSub token",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="requested",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="WebHub subscription requested at"
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="subscribed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="WebHub subscribed until"
            ),
        ),
    ]
