# Generated by Django 4.2.1 on 2023-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0044_podcast_websub_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
