# Generated by Django 4.2.1 on 2023-06-08 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0045_podcast_websub_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="num_websub_retries",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_expires",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_hub",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_mode",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_requested",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_secret",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_topic",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_verified",
        ),
    ]
