# Generated by Django 5.2.7 on 2025-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0045_remove_podcast_podcasts_po_itunes__d69e24_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="podcasts_ca_name_604e91_idx"),
        ),
    ]
