# Generated by Django 5.2.7 on 2025-10-28 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0046_category_podcasts_ca_name_604e91_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
