# Generated by Django 4.2.1 on 2023-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0046_remove_podcast_num_websub_retries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="pinged",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
