# Generated by Django 3.2.7 on 2021-09-19 10:01

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0046_auto_20210919_0902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="websub_exception",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="websub_hub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="websub_requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="websub_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
