# Generated by Django 4.2.1 on 2023-06-09 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0047_podcast_pinged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="pinged",
        ),
    ]
