# Generated by Django 3.2.7 on 2021-09-20 07:33

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0047_auto_20210919_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_secret",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
