# Generated by Django 5.2.8 on 2025-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0047_remove_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_episodes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
