# Generated by Django 4.2.1 on 2023-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0048_remove_podcast_pinged"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="parser_method",
            field=models.CharField(
                choices=[("polling", "Polling"), ("pubsub", "Pubsub")],
                default="polling",
                max_length=12,
            ),
        ),
    ]
