# Generated by Django 5.2.8 on 2025-11-12 21:16

import itertools

from django.db import migrations
from django.db.models import Count, OuterRef, Subquery


def set_podcast_num_episodes(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Episode = apps.get_model("episodes", "Episode")

    episodes_count = (
        Episode.objects.filter(podcast_id=OuterRef("pk"))
        .values("podcast_id")
        .annotate(count=Count("id"))
        .values("count")
    )
    podcast_ids = Podcast.objects.filter(
        pub_date__isnull=False,
        num_episodes=0,
    ).values_list("id", flat=True)

    for batch in itertools.batched(podcast_ids, 1000, strict=False):
        Podcast.objects.filter(id__in=batch).update(
            num_episodes=Subquery(episodes_count)
        )


def reverse_set_podcast_num_episodes(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(num_episodes__gt=0).update(num_episodes=0)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0048_podcast_num_episodes"),
    ]

    operations = [
        migrations.RunPython(
            set_podcast_num_episodes,
            reverse_set_podcast_num_episodes,
        ),
    ]
