# Generated by Django 5.2.8 on 2025-11-12 21:16

import itertools

from django.db import migrations


def set_podcast_num_episodes(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")

    podcast_ids = Podcast.objects.values_list("id", flat=True)

    for batch in itertools.batched(podcast_ids, 1000, strict=False):
        podcasts = Podcast.objects.filter(id__in=batch)
        to_update = []
        for podcast in podcasts:
            podcast.num_episodes = podcast.episodes.count()
            to_update.append(podcast)
        Podcast.objects.bulk_update(to_update, ["num_episodes"])


def reverse_set_podcast_num_episodes(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(num_episodes__gt=0).update(num_episodes=0)


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0048_podcast_num_episodes"),
    ]

    operations = [
        migrations.RunPython(
            set_podcast_num_episodes,
            reverse_set_podcast_num_episodes,
        ),
    ]
