# Generated by Django 3.2.7 on 2021-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0048_podcast_websub_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
