# Generated by Django 4.2.1 on 2023-06-10 06:34

from django.db import migrations
from django.db.models import Exists, OuterRef


def set_default_parser_method(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Subscription = apps.get_model("websub", "Subscription")

    podcasts = Podcast.objects.annotate(
        is_websub=Exists(
            Subscription.objects.filter(podcast=OuterRef("pk"), pinged__isnull=False)
        ),
    ).filter(is_websub=True)

    podcasts.update(parser_method="pubsub")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0049_podcast_parser_method"),
    ]

    operations = [
        migrations.RunPython(
            set_default_parser_method,
            reverse_code=migrations.RunPython.noop,
        )
    ]
