# Generated by Django 4.2.2 on 2023-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0050_set_default_parser_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="pinged",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
