# Generated by Django 3.2.7 on 2021-09-22 08:46

from __future__ import annotations

from django.db import migrations


def set_scheduled_none(apps, schema_editor):
    podcast_model = apps.get_model("podcasts", "Podcast")
    podcast_model.objects.filter(websub_subscribed__isnull=False).update(scheduled=None)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0050_remove_podcast_num_episodes"),
    ]

    operations = [migrations.RunPython(set_scheduled_none, migrations.RunPython.noop)]
