# Generated by Django 4.2.2 on 2023-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0050_remove_podcast_parser_method_remove_podcast_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
