# Generated by Django 5.2.8 on 2025-11-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0050_podcast_has_similar_podcasts"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
