# Generated by Django 4.2.2 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0051_podcast_queued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
