# Generated by Django 4.2.2 on 2023-06-10 08:35

from django.db import migrations
from django.db.models import F


def set_default_pinged(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(parser_method="pubsub", pinged__isnull=True).update(
        pinged=F("parsed")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0051_podcast_pinged"),
    ]

    operations = [
        migrations.RunPython(set_default_pinged, reverse_code=migrations.RunPython.noop)
    ]
