# Generated by Django 3.2.8 on 2021-10-05 18:35

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0052_auto_20210928_0709"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_schedul_e5e73a_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
