# Generated by Django 4.2.4 on 2023-08-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0053_rename_link_podcast_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="parser_error",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate", "Duplicate"),
                    ("inaccessible", "Inaccessible"),
                    ("invalid_data", "Invalid Data"),
                    ("invalid_rss", "Invalid RSS"),
                    ("not_modified", "Not Modified"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
