# Generated by Django 4.2.2 on 2023-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0053_remove_podcast_parser_method_remove_podcast_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="pubsub",
            field=models.BooleanField(default=False),
        ),
    ]
