# Generated by Django 5.2.8 on 2025-11-14 22:28

from django.db import migrations

_ITUNES_GENRE_IDS = (
    (1301, "Arts"),
    (1302, "Personal Journals"),
    (1303, "Comedy"),
    (1304, "Education"),
    (1305, "Kids & Family"),
    (1306, "Food"),
    (1309, "TV & Film"),
    (1310, "Music"),
    (1314, "Religion & Spirituality"),
    (1318, "Technology"),
    (1320, "Places & Travel"),
    (1321, "Business"),
    (1324, "Society & Culture"),
    (1402, "Design"),
    (1405, "Performing Arts"),
    (1406, "Visual Arts"),
    (1410, "Careers"),
    (1412, "Investing"),
    (1438, "Buddhism"),
    (1439, "Christianity"),
    (1440, "Islam"),
    (1441, "Judaism"),
    (1443, "Philosophy"),
    (1444, "Spirituality"),
    (1459, "Fashion & Beauty"),
    (1463, "Hinduism"),
    (1482, "Books"),
    (1483, "Fiction"),
    (1484, "Drama"),
    (1485, "Science Fiction"),
    (1486, "Comedy Fiction"),
    (1487, "History"),
    (1488, "True Crime"),
    (1489, "News"),
    (1490, "Business News"),
    (1491, "Management"),
    (1492, "Marketing"),
    (1493, "Entrepreneurship"),
    (1494, "Non-Profit"),
    (1495, "Improv"),
    (1496, "Comedy Interviews"),
    (1497, "Stand Up"),
    (1498, "Language Learning"),
    (1499, "How-To"),
    (1500, "Self-Improvement"),
    (1501, "Courses"),
    (1502, "Leisure"),
    (1503, "Automotive"),
    (1504, "Aviation"),
    (1505, "Hobbies"),
    (1506, "Crafts"),
    (1507, "Games"),
    (1508, "Home & Garden"),
    (1509, "Video Games"),
    (1510, "Animation & Manga"),
    (1511, "Government"),
    (1512, "Health & Fitness"),
    (1513, "Alternative Health"),
    (1514, "Fitness"),
    (1515, "Nutrition"),
    (1516, "Sexuality"),
    (1517, "Mental Health"),
    (1518, "Medicine"),
    (1519, "Education for Kids"),
    (1520, "Stories for Kids"),
    (1521, "Parenting"),
    (1522, "Pets & Animals"),
    (1523, "Music Commentary"),
    (1524, "Music History"),
    (1525, "Music Interviews"),
    (1526, "Daily News"),
    (1527, "Politics"),
    (1528, "Tech News"),
    (1529, "Sports News"),
    (1530, "News Commentary"),
    (1531, "Entertainment News"),
    (1532, "Religion"),
    (1533, "Science"),
    (1534, "Natural Sciences"),
    (1535, "Social Sciences"),
    (1536, "Mathematics"),
    (1537, "Nature"),
    (1538, "Astronomy"),
    (1539, "Chemistry"),
    (1540, "Earth Sciences"),
    (1541, "Life Sciences"),
    (1542, "Physics"),
    (1543, "Documentary"),
    (1544, "Relationships"),
    (1545, "Sports"),
    (1546, "Soccer"),
    (1547, "Football"),
    (1548, "Basketball"),
    (1549, "Baseball"),
    (1550, "Hockey"),
    (1551, "Running"),
    (1552, "Rugby"),
    (1553, "Golf"),
    (1554, "Cricket"),
    (1555, "Wrestling"),
    (1556, "Tennis"),
    (1557, "Volleyball"),
    (1558, "Swimming"),
    (1559, "Wilderness"),
    (1560, "Fantasy Sports"),
    (1561, "TV Reviews"),
    (1562, "After Shows"),
    (1563, "Film Reviews"),
    (1564, "Film History"),
    (1565, "Film Interviews"),
)


def set_itunes_genre_ids(apps, schema_editor):
    Category = apps.get_model("podcasts", "Category")

    categories_dct = Category.objects.select_for_update().in_bulk(field_name="name")

    for_update = []

    for genre_id, genre_name in _ITUNES_GENRE_IDS:
        if category := categories_dct.get(genre_name):
            category.itunes_genre_id = genre_id
            for_update.append(category)

    Category.objects.bulk_update(for_update, ["itunes_genre_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0054_category_itunes_genre_id"),
    ]

    operations = [
        migrations.RunPython(
            set_itunes_genre_ids,
            reverse_code=migrations.RunPython.noop,
        )
    ]
