# Generated by Django 3.2.8 on 2021-10-08 04:49

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0055_auto_20211006_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="succeeded",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-succeeded", "-pub_date"],
                name="podcasts_po_succeed_2b570a_idx",
            ),
        ),
    ]
