# Generated by Django 3.2.8 on 2021-10-08 04:49

from __future__ import annotations

from django.db import migrations, models


def set_succeeded(apps, schema_editor):
    apps.get_model("podcasts", "Podcast").objects.update(succeeded=models.F("pub_date"))


def set_succeeded_none(apps, schema_editor):
    apps.get_model("podcasts", "Podcast").objects.update(succeeded=None)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0056_auto_20211008_0449"),
    ]

    operations = [
        migrations.RunPython(
            set_succeeded,
            set_succeeded_none,
        )
    ]
