# Generated by Django 5.2.8 on 2025-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0057_set_category_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
