# Generated by Django 5.2.8 on 2025-11-18 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0058_alter_category_slug"),
    ]

    operations = [
        migrations.RunSQL(
            """
DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;
CREATE TRIGGER podcast_update_search_trigger
BEFORE INSERT OR UPDATE OF title, owner, search_vector
ON podcasts_podcast
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english',
    title, owner
);""",
            reverse_sql="""
DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;
CREATE TRIGGER podcast_update_search_trigger
BEFORE INSERT OR UPDATE OF title, owner, keywords, search_vector
ON podcasts_podcast
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english',
    title, owner, keywords
);
""",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="keywords",
        ),
    ]
