# Generated by Django 5.2.8 on 2025-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0059_remove_podcast_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="keywords",
            field=models.TextField(blank=True),
        ),
    ]
