# Generated by Django 3.2.8 on 2021-10-08 07:25

from __future__ import annotations

from django.db import migrations, models


def set_changed(apps, schema_editor):
    apps.get_model("podcasts", "Podcast").objects.update(changed=models.F("pub_date"))


def set_changed_none(apps, schema_editor):
    apps.get_model("podcasts", "Podcast").objects.update(changed=None)


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0059_auto_20211008_0724"),
    ]

    operations = [
        migrations.RunPython(
            set_changed,
            set_changed_none,
        )
    ]
