# Generated by Django 3.2.8 on 2021-10-08 09:11

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0060_set_changed_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="succeeded",
        ),
    ]
