# Generated by Django 5.2.8 on 2025-11-22 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0061_update_podcast_search_trigger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_podcast_lwr_title_idx",
        ),
    ]
