# Generated by Django 3.2.8 on 2021-10-09 12:09

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0062_auto_20211009_0629"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["scheduled"], name="podcasts_po_schedul_5829f7_idx"
            ),
        ),
    ]
