# Generated by Django 5.2.8 on 2025-11-22 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0062_remove_podcast_podcasts_podcast_lwr_title_idx"),
    ]

    operations = [
        migrations.RunSQL(
            """
DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;
CREATE TRIGGER podcast_update_search_trigger
BEFORE INSERT OR UPDATE OF title, owner, keywords, search_vector
ON podcasts_podcast
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.simple',
    title, owner, keywords
);""",
            reverse_sql="""
DROP TRIGGER IF EXISTS podcast_update_search_trigger ON podcasts_podcast;
CREATE TRIGGER podcast_update_search_trigger
BEFORE INSERT OR UPDATE OF title, owner, keywords, search_vector
ON podcasts_podcast
FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.english',
    title, owner, keywords
);
""",
        )
    ]
