# Generated by Django 3.2.8 on 2021-10-11 06:36

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0063_podcast_podcasts_po_schedul_5829f7_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_schedul_5829f7_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(fields=["scheduled", "-pub_date"], name="podcasts_po_schedul_e5e73a_idx"),
        ),
    ]
