# Generated by Django 5.2.8 on 2025-11-23 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0063_update_podcast_search_trigger_with_simple"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_fdc955_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["promoted", "language", "-pub_date"],
                name="podcasts_po_promote_54fdb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-promoted", "parsed", "updated"],
                name="podcasts_po_promote_a89157_idx",
            ),
        ),
    ]
