# Generated by Django 3.2.8 on 2021-10-13 08:53

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0064_auto_20211011_0636"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_schedul_e5e73a_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["scheduled", "-pub_date", "parsed"],
                name="podcasts_po_schedul_dd36d8_idx",
            ),
        ),
    ]
