# Generated by Django 3.2.8 on 2021-10-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0067_podcast_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="frequency",
        ),
    ]
