# Generated by Django 3.2.8 on 2021-10-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0068_remove_podcast_frequency"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_schedul_dd36d8_idx",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
