# Generated by Django 6.0 on 2025-12-07 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0069_category_search_vector_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER category_update_search_trigger
BEFORE INSERT OR UPDATE OF name ON podcasts_category
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
    search_vector, 'pg_catalog.simple', name
);
UPDATE podcasts_category SET name = name;""",
            reverse_sql="DROP TRIGGER IF EXISTS category_update_search_trigger ON podcasts_category;",
        ),
    ]
