# Generated by Django 3.2.8 on 2021-10-23 10:55

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0072_podcast_queued"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="parsed",
            new_name="polled",
        ),
    ]
