# Generated by Django 6.0 on 2025-12-09 11:10

from django.db import migrations
from django.utils import timezone


def set_default_promoted_at(apps, schema_editor) -> None:
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(promoted=True, promoted_at__isnull=True).update(
        promoted_at=timezone.now().today()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0072_remove_podcast_podcasts_po_promote_54fdb6_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_default_promoted_at,
            reverse_code=migrations.RunPython.noop,
        )
    ]
