# Generated by Django 3.2.8 on 2021-10-24 08:27

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0073_rename_parsed_podcast_polled"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="last_build_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
