# Generated by Django 6.0 on 2025-12-09 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0073_set_default_promoted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_a84cd9_idx",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-promoted_at", "language", "-pub_date"],
                name="podcasts_po_promote_ab9069_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="promoted",
        ),
    ]
