# Generated by Django 6.0 on 2025-12-09 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0074_remove_podcast_podcasts_po_promote_a84cd9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_active_aed488_idx",
        ),
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_promote_ab9069_idx",
        ),
        migrations.RenameField(
            model_name="podcast",
            old_name="promoted_at",
            new_name="promoted",
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["-promoted", "language", "-pub_date"],
                name="podcasts_po_promote_047f56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["active", "-promoted", "parsed", "updated"],
                name="podcasts_po_active_b74445_idx",
            ),
        ),
    ]
