# Generated by Django 3.2.8 on 2021-10-24 08:54

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0074_podcast_last_build_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duplicate_feed", "Duplicate Feed"),
                    ("http_error", "HTTP Error"),
                    ("invalid_rss", "Invalid RSS"),
                    ("network_error", "Network Error"),
                    ("not_modified", "Not Modified"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
