# Generated by Django 3.2.8 on 2021-11-06 13:10

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0078_podcast_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
