# Generated by Django 3.2.8 on 2021-11-07 22:09

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0079_podcast_scheduled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="polled",
            new_name="parsed",
        ),
    ]
