# Generated by Django 3.2.8 on 2021-11-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0080_rename_polled_podcast_parsed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="frequency",
        ),
    ]
