# Generated by Django 3.2.8 on 2021-11-11 06:25

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0081_remove_podcast_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="schedule_modifier",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
