# Generated by Django 6.0 on 2025-12-10 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0082_remove_category_search_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="has_similar_podcasts",
        ),
    ]
