# Generated by Django 3.2.9 on 2021-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0082_podcast_schedule_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="hub",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
