# Generated by Django 3.2.9 on 2021-11-12 10:33

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0083_podcast_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="hub_exception",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="last_subscribe_callback",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="subscribe_requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="subscribe_status",
            field=models.CharField(
                choices=[
                    ("unsubscribed", "Unsubscribed"),
                    ("subscribed", "Subscribed"),
                    ("requested", "Requested"),
                    ("error", "error"),
                ],
                default="unsubscribed",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="subscribed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Subscribed until"
            ),
        ),
    ]
