# Generated by Django 3.2.9 on 2021-11-12 11:19

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0084_auto_20211112_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="subscribe_secret",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
