# Generated by Django 3.2.9 on 2021-11-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0086_auto_20211112_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="subscribe_ping",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
