# Generated by Django 3.2.9 on 2021-11-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0087_podcast_subscribe_ping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="hub",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="hub_exception",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="subscribe_ping",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="subscribe_requested",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="subscribe_secret",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="subscribe_status",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="subscribed",
        ),
    ]
