# Generated by Django 6.0 on 2025-12-18 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0087_alter_podcast_parser_result"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="podcast",
            name="podcasts_po_content_736948_idx",
        ),
    ]
