# Generated by Django 3.2.9 on 2021-11-16 07:00

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0088_auto_20211112_2045"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_hub",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_last_called",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("requested", "Requested"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_status_changed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
