# Generated by Django 6.0 on 2025-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0090_podcast_http_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ok", "OK"),
                    ("not_modified", "Not Modified"),
                    ("invalid_rss", "Invalid RSS"),
                    ("duplicate", "Duplicate"),
                    ("discontinued", "Discontinued"),
                    ("database_error", "Database Error"),
                    ("temporary_http_error", "Temporary HTTP Error"),
                    ("permanent_http_error", "Permanent HTTP Error"),
                ],
                max_length=30,
            ),
        ),
    ]
