# Generated by Django 3.2.9 on 2021-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0091_set_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_last_called",
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_subscribed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_token",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
