# Generated by Django 6.0 on 2025-12-20 10:37

from django.db import migrations


def update_feed_status(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    # Any podcast with feed_status 'temporary_http_error' and 'http_status' 'OK' or 'Not Modified' or NULL:
    # should have their feed_status updated to 'network_error'.
    #
    Podcast.objects.filter(
        feed_status="temporary_http_error",
    ).filter(http_status__in=(200, 304)).update(feed_status="network_error")

    Podcast.objects.filter(
        feed_status="temporary_http_error",
    ).exclude(http_status__isnull=True).update(feed_status="network_error")

    # Any other podcast with feed_status 'temporary_http_error' should have their feed_status updated to 'transient_feed_error'.
    Podcast.objects.filter(
        feed_status="temporary_http_error",
    ).update(feed_status="transient_feed_error")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0093_alter_podcast_feed_status"),
    ]

    operations = [
        migrations.RunPython(
            update_feed_status,
            reverse_code=migrations.RunPython.noop,
        )
    ]
