# Generated by Django 3.2.9 on 2021-11-17 08:30

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0094_podcast_websub_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_exception",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_hub",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_status",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_status_changed",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_subscribed",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_token",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="websub_url",
        ),
    ]
