# Generated by Django 6.0 on 2025-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0096_update_feed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ok", "OK"),
                    ("not_modified", "Not Modified"),
                    ("invalid_rss", "Invalid RSS"),
                    ("duplicate", "Duplicate"),
                    ("discontinued", "Discontinued"),
                    ("database_error", "Database Error"),
                    ("network_error", "Network Error"),
                ],
                max_length=30,
            ),
        ),
    ]
