# Generated by Django 6.0 on 2025-12-20 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0097_alter_podcast_feed_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="feed_status",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="http_status",
        ),
    ]
