# Generated by Django 3.2.9 on 2021-11-19 16:49

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0098_remove_podcast_podcastindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_failures",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
