# Generated by Django 6.0 on 2025-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0099_podcast_feed_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="exception",
            field=models.TextField(blank=True),
        ),
    ]
