# Generated by Django 3.2.9 on 2021-11-24 17:27

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0100_remove_podcast_frequency_modifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="scheduled",
        ),
    ]
