# Generated by Django 6.0 on 2025-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0100_podcast_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="traceback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="exception",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
