# Generated by Django 6.0 on 2025-12-20 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0101_podcast_traceback_alter_podcast_exception"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="traceback",
        ),
    ]
