# Generated by Django 3.2.9 on 2021-11-25 09:41

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0101_remove_podcast_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="frequency_modifier",
            field=models.FloatField(default=1.0),
        ),
    ]
