# Generated by Django 3.2.9 on 2021-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0102_podcast_frequency_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="frequency_modifier",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
