# Generated by Django 6.0 on 2025-12-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0103_alter_podcast_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("not_modified", "Not Modified"),
                    ("discontinued", "Discontinued"),
                    ("duplicate", "Duplicate"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
