# Generated by Django 3.2.9 on 2021-11-29 19:38

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0105_auto_20211129_1905"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_token",
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_secret",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
