# Generated by Django 3.2.9 on 2021-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0106_auto_20211129_1938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_lease",
        ),
        migrations.AddField(
            model_name="podcast",
            name="websub_timeout",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
