# Generated by Django 6.0 on 2025-12-23 21:57

from django.db import migrations


def update_database_error_status(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    Podcast.objects.filter(feed_status="error").update(feed_status="database_error")


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0107_alter_podcast_feed_status"),
    ]

    operations = [
        migrations.RunPython(
            update_database_error_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
