# Generated by Django 3.2.9 on 2021-11-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0108_podcast_websub_callback_exception"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="websub_callback_exception",
        ),
    ]
