# Generated by Django 3.2.9 on 2021-11-30 10:11

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0109_remove_podcast_websub_callback_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="websub_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
