# Generated by Django 6.0 on 2025-12-24 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0109_alter_podcast_feed_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="feed_last_updated",
        ),
    ]
