# Generated by Django 3.2.9 on 2021-12-01 10:04

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0110_podcast_websub_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="podping",
            field=models.BooleanField(default=False),
        ),
    ]
