# Generated by Django 6.0.2 on 2026-02-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0110_remove_podcast_feed_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="exception",
        ),
        migrations.AlterField(
            model_name="podcast",
            name="feed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("not_modified", "Not Modified"),
                    ("discontinued", "Discontinued"),
                    ("duplicate", "Duplicate"),
                    ("invalid_rss", "Invalid RSS"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
