# Generated by Django 3.2.9 on 2021-12-01 22:22

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0112_auto_20211201_2050"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="frequency_modifier",
        ),
    ]
