# Generated by Django 3.2.9 on 2021-12-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0113_remove_podcast_frequency_modifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="frequency",
        ),
    ]
