# Generated by Django 3.2.9 on 2021-12-03 06:19

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0114_remove_podcast_frequency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="num_failures",
            new_name="errors",
        ),
    ]
