# Generated by Django 3.2.9 on 2021-12-05 23:01

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0115_rename_num_failures_podcast_errors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="podping",
        ),
    ]
