# Generated by Django 4.0 on 2021-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0116_remove_podcast_podping"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
