# Generated by Django 4.0 on 2021-12-14 22:02

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0118_remove_podcast_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="feed_queue",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
