# Generated by Django 4.0.4 on 2022-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0122_podcast_podcasts_po_promote_fdc955_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_podcasts_subscription",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "podcast"),
                name="unique_podcasts_subscription_user_podcast",
            ),
        ),
    ]
