# Generated by Django 4.0.4 on 2022-05-03 10:00

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0123_remove_subscription_unique_podcasts_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="feed_queue",
        ),
    ]
