# Generated by Django 4.0.4 on 2022-05-03 19:54

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0124_remove_podcast_feed_queue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
