# Generated by Django 4.0.4 on 2022-05-13 13:02

from __future__ import annotations

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0125_remove_podcast_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="refresh_interval",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
