# Generated by Django 4.0.4 on 2022-06-01 15:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0127_remove_podcast_refresh_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="refresh_interval",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
