# Generated by Django 4.0.5 on 2022-06-05 15:58

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0128_podcast_refresh_interval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="refresh_interval",
            new_name="update_interval",
        ),
    ]
