# Generated by Django 4.0.5 on 2022-06-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0129_rename_refresh_interval_podcast_update_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="update_interval",
        ),
    ]
