# Generated by Django 4.0.5 on 2022-06-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0131_podcast_update_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="update_interval",
        ),
    ]
