# Generated by Django 4.0.5 on 2022-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0134_remove_podcast_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
