# Generated by Django 4.0.5 on 2022-06-15 07:03

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0137_set_removed_from_http_gone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
