# Generated by Django 4.0.5 on 2022-06-15 13:38

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0139_remove_podcast_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="errors",
        ),
    ]
