# Generated by Django 4.0.5 on 2022-06-16 17:30

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0141_podcast_queued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="queued",
        ),
    ]
