# Generated by Django 4.0.6 on 2022-07-14 07:34

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0144_alter_podcast_parse_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="num_retries",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
