# Generated by Django 4.0.6 on 2022-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0145_podcast_num_retries"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en_gb",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_fi",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
