# Generated by Django 4.0.6 on 2022-07-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0146_category_name_en_category_name_en_gb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name_en_gb",
        ),
    ]
