# Generated by Django 4.0.6 on 2022-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0149_rename_user_subscription_subscriber'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_podcasts_subscription_user_podcast',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'podcast'), name='unique_podcasts_subscription_user_podcast'),
        ),
    ]
