apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: django-worker
    spec:
      nodeSelector:
        role: jobrunner
      containers:
        - name: django
          image: {{ .Values.image }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory|quote }}
              cpu: {{ .Values.resources.requests.cpu|quote }}
            limits:
              memory: {{ .Values.resources.limits.memory|quote }}
              cpu: {{ .Values.resources.limits.cpu|quote }}
          command: ["/bin/sh", "-c"]
          args: ["./manage.sh db_worker"]
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secrets
