apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        role: database
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          resources:
            requests:
              memory: {{ .Values.resources.postgres.requests.memory|quote }}
              cpu: {{ .Values.resources.postgres.requests.cpu|quote }}
            limits:
              memory: {{ .Values.resources.postgres.limits.memory|quote }}
              cpu: {{ .Values.resources.postgres.limits.cpu|quote }}
          args: {{ .Values.postgres.args | toYaml | nindent 12 }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-storage
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 3
            failureThreshold: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-{{ include "radiofeed.postgresVersion" . }}
