apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-{{ include "radiofeed.postgresVersion" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
