apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ include "radiofeed.postgresVersion" . }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: {{ .Values.postgres.volumePath|quote }}
