apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://postgres:%s@postgres.%s.svc.cluster.local:5432/postgres" .Values.secrets.postgresPassword .Release.Namespace | quote }}
  MAILGUN_API_KEY: {{ .Values.secrets.mailgunApiKey|quote }}
  OPEN_TELEMETRY_URL: {{ .Values.secrets.openTelemetryUrl|quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword|quote }}
  PWA_SHA256_FINGERPRINTS: {{ .Values.secrets.pwaSha256Fingerprints|quote }}
  REDIS_URL: {{ printf "redis://redis.%s.svc.cluster.local:6379/0" .Release.Namespace | quote }}
  SECRET_KEY: {{ .Values.secrets.djangoSecretKey|quote }}
  SECRET_KEY_FALLBACKS: {{ .Values.secrets.djangoSecretKeyFallbacks|quote }}
  SENTRY_URL: {{ .Values.secrets.sentryUrl|quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-cert
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.secrets.cloudflare.cert|quote }}
  tls.key: {{ .Values.secrets.cloudflare.key|quote }}
