@_default:
    @just --list

@playbook *ARGS:
    ansible-playbook -v -i hosts.yml {{ ARGS }}

@site:
    @just playbook site.yml

@deploy:
    @just playbook deploy.yml

@upgrade:
    @just playbook upgrade.yml

@djmanage:
    @just playbook dj_manage.yml

dj *ARGS:
    #!/usr/bin/bash
    if [ ! -f "./manage.sh" ]; then
        echo "manage.sh not found, generating it..."
        just djmanage
    fi
    ./manage.sh {{ ARGS }}
