# Generated by Django 3.2.9 on 2021-12-05 11:26

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("podcasts", "0115_rename_num_failures_podcast_errors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hub", models.URLField(max_length=2086)),
                ("topic", models.URLField(max_length=2086)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Requested"),
                            ("subscribed", "Subscribed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("status_changed", models.DateTimeField(blank=True, null=True)),
                ("secret", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("exception", models.TextField(blank=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("podcast", "hub", "topic"), name="unique_websub_subscription"
            ),
        ),
    ]
