# Generated by Django 3.2.9 on 2021-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0002_alter_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("denied", "Denied"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
