# Generated by Django 3.2.9 on 2021-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0003_alter_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
