# Generated by Django 3.2.9 on 2021-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0004_subscription_requested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="requested",
        ),
        migrations.AddField(
            model_name="subscription",
            name="response",
            field=models.TextField(blank=True),
        ),
    ]
