# Generated by Django 3.2.9 on 2021-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0005_auto_20211206_1148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="response",
        ),
    ]
