# Generated by Django 3.2.9 on 2021-12-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0006_remove_subscription_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="num_requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="requested",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
