# Generated by Django 3.2.9 on 2021-12-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websub", "0007_auto_20211207_0638"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="num_requests",
            new_name="requests",
        ),
    ]
