# Generated by Django 3.2.6 on 2021-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0010_auto_20210808_0657"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="queueitem",
            name="uniq_queue_item",
        ),
        migrations.AddConstraint(
            model_name="queueitem",
            constraint=models.UniqueConstraint(
                fields=("user", "episode"), name="unique_episodes_queueitem"
            ),
        ),
    ]
