# Generated by Django 3.2.6 on 2021-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0014_remove_audiolog_autoplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="code",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
