# Generated by Django 3.2.6 on 2021-08-08 10:15

import uuid

from django.db import migrations


def create_uuid_codes(apps, schema_editor):
    AudioLog = apps.get_model("episodes", "AudioLog")

    logs = AudioLog.objects.filter(code__isnull=True)
    for_update = []
    for log in logs:
        log.code = uuid.uuid4()
        for_update.append(log)

    AudioLog.objects.bulk_update(logs, fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0015_audiolog_code"),
    ]

    operations = [
        migrations.RunPython(create_uuid_codes, reverse_code=migrations.RunPython.noop)
    ]
