# Generated by Django 3.2.6 on 2021-08-08 10:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0016_create_audio_log_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolog",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
