# Generated by Django 3.2.7 on 2021-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0018_update_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolog",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
    ]
