# Generated by Django 4.0.1 on 2022-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0024_delete_queueitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="episode",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="season",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
