# Generated by Django 4.1.6 on 2023-02-08 11:04

from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("podcasts", "0014_remove_category_name_en_remove_category_name_fi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("hub", models.URLField(max_length=2086)),
                ("topic", models.URLField(max_length=2086)),
                ("secret", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("subscribed", "Subscribed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("requested", models.DateTimeField(blank=True, null=True)),
                ("status_changed", models.DateTimeField(blank=True, null=True)),
                ("exception", models.TextField(blank=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websub_subscriptions",
                        to="podcasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("podcast", "hub", "topic"), name="unique_websub_subscription"
            ),
        ),
    ]
