# Generated by Django 4.2.1 on 2023-06-08 08:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("podcasts", "0046_remove_podcast_num_websub_retries_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("hub", models.URLField(max_length=2086)),
                ("topic", models.URLField(max_length=2086)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subscribe", "Subscribe"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=12,
                    ),
                ),
                ("secret", models.UUIDField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("requested", models.DateTimeField(blank=True, null=True)),
                ("verified", models.DateTimeField(blank=True, null=True)),
                ("num_retries", models.PositiveSmallIntegerField(default=0)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websub_subscriptions",
                        to="podcasts.podcast",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("podcast", "hub"),
                name="unique_websub_subscription_websub_podcast",
            ),
        ),
    ]
