# Generated by Django 4.1.5 on 2023-02-08 13:31

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="exception",
        ),
    ]
