# Generated by Django 4.2.1 on 2023-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="pinged",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
