# Generated by Django 4.2.1 on 2023-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0002_subscription_pinged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="mode",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
