# Generated by Django 4.1.5 on 2023-02-08 13:55

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0002_remove_subscription_exception"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="mode",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
