# Generated by Django 4.1.5 on 2023-02-08 13:56

from __future__ import annotations

from django.db import migrations


def set_default_mode(apps, schema_editor):
    Subscription = apps.get_model("websub", "Subscription")

    for_update = []

    for sub in Subscription.objects.exclude(status="pending"):
        sub.mode = {
            "subscribed": "subscribe",
            "unsubscribed": "unsubscribe",
            "denied": "denied",
        }[sub.status]
        for_update.append(sub)

    Subscription.objects.bulk_update(for_update, fields=["mode"])


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0003_subscription_mode"),
    ]

    operations = [
        migrations.RunPython(set_default_mode, reverse_code=migrations.RunPython.noop)
    ]
