# Generated by Django 4.2.1 on 2023-06-08 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0003_alter_subscription_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="pinged",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="requested",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="verified",
        ),
    ]
