# Generated by Django 4.1.5 on 2023-02-08 14:05

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0004_set_default_modes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="status",
        ),
    ]
