# Generated by Django 4.2.1 on 2023-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0004_remove_subscription_pinged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="confirmed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pinged",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
