# Generated by Django 4.2.2 on 2023-06-10 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0005_subscription_confirmed_subscription_pinged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="confirmed",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="pinged",
        ),
    ]
