# Generated by Django 4.1.5 on 2023-02-08 14:13

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0005_remove_subscription_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="status_changed",
            new_name="verified",
        ),
    ]
