# Generated by Django 4.1.5 on 2023-02-08 14:17

from __future__ import annotations

from datetime import timedelta

from django.db import migrations
from django.db.models import F

_DEFAULT_LEASE_SECONDS = 24 * 60 * 60 * 7  # 1 week


def set_default_expires(apps, schema_editor):
    Subscription = apps.get_model("websub", "Subscription")

    Subscription.objects.filter(mode="subscribe", expires__isnull=True).update(
        expires=F("verified") + timedelta(seconds=_DEFAULT_LEASE_SECONDS)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0006_rename_status_changed_subscription_verified"),
    ]

    operations = [
        migrations.RunPython(
            set_default_expires, reverse_code=migrations.RunPython.noop
        )
    ]
