# Generated by Django 4.1.6 on 2023-02-08 14:34

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0007_set_default_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("subscribe", "Subscribe"),
                    ("unsubscribe", "Unsubscribe"),
                    ("denied", "Denied"),
                ],
                max_length=12,
            ),
        ),
    ]
