# Generated by Django 4.1.6 on 2023-02-08 16:51

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websub", "0008_alter_subscription_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="verified",
        ),
    ]
