# Generated by Django 4.2.7 on 2023-11-01 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER episode_update_search_trigger
BEFORE INSERT OR UPDATE OF title, keywords, search_vector
ON episodes_episode
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(search_vector, 'pg_catalog.english', title, keywords);
UPDATE episodes_episode SET search_vector = NULL;""",
            reverse_sql="DROP TRIGGER IF EXISTS episode_update_search_trigger ON episodes_episode;",
        ),
    ]
