# Generated by Django 5.1.1 on 2024-10-02 22:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0006_remove_subscription_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="frequency",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
