# Generated by Django 5.1.7 on 2025-03-09 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0014_podcast_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(fields=["rating"], name="podcasts_po_rating_f96c31_idx"),
        ),
    ]
