# Generated by Django 5.1.7 on 2025-03-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0024_alter_podcast_parser_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="Podcast marked complete, no new episodes will be added.",
            ),
        ),
    ]
