# Generated by Django 5.1.7 on 2025-03-21 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0028_remove_podcast_complete"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recommendation",
            name="podcasts_re_podcast_10c46d_idx",
        ),
        migrations.RemoveIndex(
            model_name="recommendation",
            name="podcasts_re_recomme_244ce9_idx",
        ),
    ]
