# Generated by Django 5.2.2 on 2025-06-07 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0038_alter_podcast_itunes_ranking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["itunes_ranking", "-pub_date"],
                name="podcasts_po_itunes__d69e24_idx",
            ),
        ),
    ]
